---
# Text Prep

In [1]:
from sentence_transformers import SentenceTransformer
import operator
import regex as re
from pandas import DataFrame
import numpy as np
import umap
#import hdbscan
import matplotlib.pyplot as plt
import pandas as pd
import PyPDF2
import cleantext
from cleantext import clean

In [2]:
pdfFileObj = open('/Users/kazotogbah/Desktop/CapstoneImplementation/HMH_IntoReading_G5_TeachersGuide_v01.pdf','rb')
pdfReader = PyPDF2.PdfFileReader('/Users/kazotogbah/Desktop/CapstoneImplementation/HMH_IntoReading_G5_TeachersGuide_v01.pdf')

pagecount = pdfReader.getNumPages ()

pagevector = []
for count in range(pagecount):
    page = pdfReader.getPage(count)
    page_extract = page.extractText ()
    pagevector.append(page_extract)
pagevector

['GRADE 5\nTeacher™s \nGuide\nVolume\n1',
 'Authors and Advisors\nAlma Flor Ada Ł Kylene Beers Ł F. Isabel Campoy\nJoyce Armstrong Carroll Ł Nathan Clemens\nAnne Cunningham Ł Martha C. Hougen\nElena Izquierdo Ł Carol Jago Ł Erik Palmer \nRobert E. Probst Ł Shane Templeton Ł Julie Washington\nContributing Consultants\nDavid Dockterman Ł Mindset Works®\nJill Eggleton\nGRADE 5 Ł\n VOLUME 1\nTeacher™s Guide\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'Copyright © 2020 by Houghton Mifflin Harcourt Publishing Company\nAll rights reserved.  No part of this work may be reproduced or transmitted in any form or by any means, \nelectronic or mechanical, including photocopying or recording, or by any information storage or retrieval \nsystem, without the prior written permission of the copyright owner unless such copying is expressly \npermitted by federal copyright law.\nPermission is hereby granted to individuals using the corresponding student™s textbook or kit as the major \nvehicle for regular classroom instruction to photocopy Rubrics and Backmatter pages from this publication \nin classroom quantities for instructional use and not for resale.  Requests for information on other matters \nregarding duplication of this work should be submitted through our Permissions website at https://\ncustomercare.hmhco.com/contactus/Permissions.html or mailed to Houghton Mifflin Harcourt Publishing \nCompany, Attn: Intellectual Property Licensing, 9400 Southpark Center Loop, Orlando, Florida 32819-8647.\nPrinted in the U.S.A.\nISBN   978-0-544-46144-4\n \n1 2 3 4 5 6 7 8 9 10   XXXX    27 26 25 24 23 22 21 20 19 18\n4500000000\n \nB C D E F G\nIf you have received these materials as examination copies free of charge, Houghton Mifflin Harcourt \nPublishing Company retains title to the materials and they may not be resold.  Resale of examination \ncopies is strictly prohibited.\nPossession of this publication in print format does not entitle users to convert this publication, or any \nportion of it, into electronic format. \nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'CONTENTS\nPROGRAM OVERVIEW\nAuthors and Advisors˜\n \n˜ivŒv\nDevelop Collaborative,  \nSelf-Directed Learners˜\n \n˜viŒvii\nBuild Content Knowledge  \nThrough Multi-Genre Text Sets˜\n \n˜viiiŒix\nFoster Critical Thinking and  \nDeep Analysis of Text˜\n \n˜xŒxi\nNotice & Note: Strategies for Close Reading˜\n \n˜xi\nMake Meaningful Connections  \nBetween Reading and Writing˜\n \n˜xiiŒxiii\nSupport Vocabulary and Language \nDevelopment˜\n \n˜xiv\nDevelop Research and  \nCommunication Skills˜\n \n˜xv\nUse Technology to Enhance  \nInstruction˜\n \n˜xviŒxvii\nMaximize Growth Through Data-Driven  \nDifferentiation and Assessment˜\n \n˜xviiiŒxix\nFlexible Resources for Responsive  \nTeaching˜\n \n˜xxŒxxi\nFoster a Mindset for Learning˜\n \n˜xxii\nConnect with Families and Community˜\n \n˜xxii\nBuild a Culture of Professional Growth˜\n \n˜xxiii\nStudent and Teacher Materials˜\n \n˜xxivŒxxv\nVolume Contents˜\n \n˜xxviŒxxxvii\nSmall-Group Reading˜\n \n˜xxxviii\nWelcome to \n \nHMH Into Reading\nŽ\nHoughton Mifflin Harcourt is delighted to welcome you to our brand-new \nliteracy program. \nHMH Into Reading\nŽ combines the best practices of \nbalanced literacy with comprehensive coverage of \nEnglish Language Arts \ncurriculum standards\n.\nThe authors and consultants who contributed to \nInto Reading\n share a deep \ncommitment to education and a passion for learning. We look forward to \nsharing the story of our program with youŠand to helping all of your students \nget \nInto Reading\n and become lifelong learners.\nDO NOT EDIT--Changes must be made through "File info" \nCorrectionKey=NL-B\n',
 'HMH Into Reading\nŽ\n Authors and Advisors\nCarol Jago, M.A.\nNationally known author and lecturer on reading \nand writing with 32 years of classroom \nexperience; author of \nWith Rigor for All\n and the \nforthcoming \nThe Book in Question: How and Why \nReading Is in Crisis\n; national consultant who \nfocuses on text complexity, genre instruction, \nand the use of appropriate literature in the KŒ12 \nclassroom\nErik Palmer, M.A.\nVeteran teacher and consultant whose work \nfocuses on how to teach oral communication \nand good thinking (argument, persuasion, and \nreasoning), and how to use technology in the \nclassroom to improve instruction; author of \nWell \nSpoken\n and \nGood Thinking\nRobert E. Probst, Ph.D.\nProfessor Emeritus, Georgia State University; \nnationally known literacy consultant to national \nand international schools; author of \nResponse & \nAnalysis\n and coauthor of \nDisruptive Thinking\n, \nNotice & Note: Strategies for Close Reading\n, and \nReading Nonfiction: Notice & Note Stances, \nSignposts, and Strategies\nShane Templeton, Ph.D.\nFoundation Professor Emeritus of Literacy \nStudies at the University of Nevada, Reno; \nresearcher and practitioner with a focus on \ndevelopmental word knowledge; author of \nWords Their Way\nJulie Washington, Ph.D.\nProfessor, Georgia State University; researcher \nwith an emphasis on the intersection of cultural \ndialect use, literacy attainment, and academic \nperformance; author of numerous articles on \nlanguage and reading development, and on \nlanguage disorders in urban children growing up \nin poverty; consultant for \niRead\n, \nSystem 44\n, and \nREAD 180\n Universal\nKylene Beers, Ed.D.\nNationally known lecturer and author on reading \nand literacy; national and international \nconsultant dedicated to improving literacy, \nparticularly for striving readers; coauthor of \nDisruptive Thinking\n, \nNotice & Note: Strategies for \nClose Reading\n, and \nReading Nonfiction: Notice & \nNote Stances, Signposts, and Strategies\nJoyce Armstrong Carroll, Ed.D., H.L.D.\nNationally known consultant on the teaching of \nwriting, with classroom experience in every \ngrade from primary through graduate school; \ncodirector of Abydos Literacy Learning, which \ntrains teachers in writing instruction; coauthor of \nActs of Teaching: How to Teach Writing\nNathan Clemens, Ph.D.\nAssociate Professor, University of Texas, Austin; \nresearcher and educator with a focus on \nimproving instruction, assessment, and \nintervention for students with reading difficulties \nin kindergarten through adolescence\nAnne Cunningham, Ph.D.\nProfessor, University of California, Berkeley; \nnationally recognized researcher on literacy and \ndevelopment across the life span; coauthor of \nBook Smart: How to Develop and Support \nSuccessful, Motivated Readers\nMartha C. Hougen, Ph.D.\nTeacher educator focused on reforming educator \npreparation to better address the diverse needs \nof students; coeditor and contributing author of \nFundamentals of Literacy Instruction & Assessment \nPre-KŒ6\niv\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'Into Reading\n and \n¡Arriba la lectura!\n \nAlma Flor Ada, Ph.D.\nProfessor Emerita, University of San Francisco; \ninternationally renowned expert in bilingual \nliterature and literacy; author of over 200 award-\nwinning books, both academic and for young \nreaders; a leading mentor in transformative \neducation\nF. Isabel Campoy \nAward-winning bilingual author of over 150 \nchildren™s books of poetry, theater, stories, \nbiographies, art, and culture; internationally \nrecognized scholar, educator, and translator; a \nmember of the North American Academy of \nSpanish Language\nElena Izquierdo, Ph.D.\nAssociate Professor of teacher education at the \nUniversity of Texas, El Paso; researcher and \npractitioner with a focus on dual-language \neducation, biliteracy, and educational equity for \nEnglish learners\nContributing Consultants \nDavid Dockterman, Ed.D.\nLecturer at Harvard University Graduate School \nof Education whose work focuses on turning \nresearch into effective, innovative practice to \nmeet the variable needs of all learners; advisor \non \nMATH 180 \nand \nREAD 180 \nUniversal\nJill Eggleton, QSO (Queen™s Service Order \nin Literacy and Education), Ed.D. \nLeading balanced-literacy expert, international \nconsultant, and teacher with over 35 years of \nteaching and administration experience; trains \nand inspires educators in how to incorporate \nbalanced-literacy methods in the classroom; \nAdjunct Professor, Sioux Falls University; \nMargaret Mahy Literacy Medal award winner; \nauthor of over 1,000 children™s books, poetry, \nand teacher resources\nv\nWelcome to \nHMH Into Reading\nŽ\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'WHOLE-GROUP \nWRAP-UP\nCOLLABORATIVE\nWORK\nINDEPENDENT\nPRACTICE\nTEACHER-LED \nSMALL GROUPS\nWHOLE-GROUP \nMINILESSON\nDevelop Collaborative, \nSelf-Directed Learners\nInto Reading™\ns \nWorkshop Model\n utilizes a \ngradual release of responsibility that sets \nstudents on a path to mastery and success.\nANCHOR CHART 17:\n  \nCentral Idea\nReading Workshop\nA quick whole-group minilesson is followed by small-group and \nindependent application time, during which students practice \ncollaboratively and on their own.\nSmall-Group Instruction\nMultiple options for small-group instruction\n allow teachers \nto meet the needs of diverse learners. \nGUIDED READING WITH LEVELED LIBRARY\nAdvance student ability with texts that engage and challenge \nreaders at their instructional level. \nFOUNDATIONAL SKILLS DEVELOPMENT\nBuild students‚ reading fluency through application of decoding \nand spelling skills and other support activities based on need. \nSKILL AND STRATEGY LESSONS\nProvide targeted support in specific skills and strategies based \non individual student needs.\nSUPPORT FOR ENGLISH LEARNERS\nProvide instruction and practice in a safe, risk-free setting, \nallowing English learners to experiment with language.\nWhole-Group Minilesson\nStudents are introduced to \nskills via \nAnchor Charts\n and \nthe shared reading of a \ncommon text.\nLearn Together\n \n15Œ20 minutes\nvi\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'WHOLE-GROUP WRAP-UP\nCOLLABORATIVE\nWORK\nINDEPENDENTPRACTICE\nTEACHER-LED \nSMALL GROUPSWHOLE-GROUP MINILESSONIndependent and Collaborative Work\nOpportunities for independent work\n allow students to practice and apply targeted \nknowledge and skills.LITERACY CENTERSEngaging activities across a variety of instructional contexts \n\nallow students to synthesize information and solidify their \nunderstanding.  READING CENTER\n˜˚˚˛\n˜˚˚˛\n˜˚˚˛\n˜˚˚˛\n˜˚˚˛  VOCABULARY CENTER\n  DIGITAL STATION\n  WRITING CENTER\n  PROJECT CENTER\nmyBOOKWrite-in student text offers opportunities to read, write, and \n\nrespond to complex texts.\nGENRE STUDY BOOK CLUBSConversation about books fosters excitement about reading and \n\nwriting.STUDENT CHOICE LIBRARY BOOKSSelf-selected reading creates an authentic opportunity for \n\nstudents to practice new skills and heighten reading engagement.\nINQUIRY AND RESEARCH PROJECTResearch- and inquiry-based activities are consistent with \n\nproject\n-based learning.Small-Group and Independent Work\n 45Œ60 minutes\nWrap-Up\n 5 minutes\nReading Workshop\nviiWelcome to\n HMH Into Reading\nŽDO NOT EDIT--Changes must be made through ﬁFile infoﬂ \nCorrectionKey=NL-B\n',
 'MODULE\nWelcome to the Module\nWEEK\n1\n6\nGenre:\n Informational Text\nLexile® Measure:\n 920L\nGenre:\n Informational Text\nmy \nBOOK\nmy \nBOOK\nThe World Around Us\nStudents view and respond to the video \nThe \nWorld Around Us\n to learn more about different \ntypes of artists and art forms.\nGenre:\n Informational Text\nLexile® Measure:\n 1010L\nGuided Reading Level:\n W\nREAD ALOUD\nGET CURIOUS VIDEO\n˜˚˛˝˙ˆˇˆ˚˚\nCarefully selected, content-rich text sets help students build topic \nknowledge and reading skills.\nREAD ALOUD\nCOMMUNICATION\nREAD-ALOUD TEXT\nWhat made Andy Warhol a multimedia \nartist?\n (A multimedia artist creates many \nforms˜of art; Warhol painted, wrote, made \nfilms,˜produced music, and published a \nmagazine.) \nDOK 1\nB\nHow did artists in the Pop Art movement \nwant to change art?\n (They thought the \ndefinition of art could be broader; it should \nbe˜mass-produced and deal with popular \ntopics.) \nDOK 2\nC\n Andy Warhol \nWhen French leader Napoleon Bonaparte claimed 200 years ago that, ﬁA \ngood sketch is better than a long speech,ﬂ he was noting the power artists \nhave in a society. The visual arts, such as paintings, photographs, movies, or \nTV shows, leave an impact that other forms of communication do not. And \nsince these visual arts often reflect the time and place in which they were \nmade, art is a \ncritical\n part of any society. \nA\nAndy Warhol was a very \ninfluential\n modern American artist. In addition to \nbeing a painter, Warhol also was a filmmaker, an author, a music producer, \nand a magazine publisher. His multimedia approach to the visual arts vastly \nexpanded Americans™ awareness of all art. His studio, known as ﬁThe \nFactory,ﬂ was a gathering place for New York City™s artists, musicians, and \nfilmmakers. His \nentrepreneurial\n styleŠhe saw himself as a businessman as \nwell as an artistŠis a model for many current creative artists.\n \nB\nWarhol is best known as a leader of the Pop Art movement. This group of \nartists believed that the existing definition of art was too narrow and \nexcluded too many people from appreciating it. At the time, something \nwas˜considered art only if it was a unique, one-of-a-kind piece dealing with \na˜serious subject. Pop artists, however, believed that art could (and should) \nbe˜made with recognizable, mass-produced, ﬁpopularﬂ items that \nsurround˜us.\n \nC\nWhat are some ways art reflects the time \nand place it is made?\n (Artists can only use the \nmaterials available in their place and time; they \nlearn from other artists who have had similar \ninterests and experiences, etc.) \nDOK 2\nA\nT239\nListening Comprehension\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=TX-A\nmy \nBOOK\nNo matter what form their creations take, all artists have similar goals. \nArtists explore what it means to be a personŠto think, feel, and be. \nThey™re interested in sharing something of themselves as well as \nprovoking emotions in other peopleŠtheir audience. Using a variety of \ntools, including words, music, paint, and movement, they make people \nlaugh, cry, fear, hope, and wonder.  \n1\nLet™s Get\nStorytelling\nPeople have been using words creatively \nfor many thousands of years. Storytelling \nbegan long before people invented writing. \nBack then, people passed stories along orally. The oldest known written story is a \nclassic\n tale, \nThe Epic of Gilgamesh\n, which pays \ntribute\n to an honored king. It was \nfirst written on clay tablets in the late second or early third millennium B.C.E. \nToday™s storytellers have many ways to share their work: books, plays, \nscreenplays, magazines, and blogs. Even tweets and text messages can be creative. \nWriters can use words, letters, and even emojis to communicate ideas. \nWriters™ stories describe places, people, and events of all kinds. Some are \nfantastic, such as an interplanetary friendship set in the distant future. Others are \nmore realistic, such as a lonely student struggling to fit in at a new school. Writers \noften use dialogue to help readers understand characters™ relationships, \nmoods, and motives.\n2\n3\n4\nCREATIVE\n˜˚˛˝˙\nˆ\nmyNotes\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\nCorrectionKey=TX-A\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\nCorrectionKey=TX-A\n16\n5re_se_m6_ma.indd   16\n3/8/2018   3:39:18 AM\nmy \nBOOK\nCHRISTO \nAND\n JEANNE-CLAUDE\nTHROUGH THE GATES \nAND\n BEYOND\nJAN GREENBERG \nAND\n SANDRA JORDAN\nmyNotes\n19\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\nCorrectionkey=TX-B;NL-B\n5re_se_m6_christo.indd   19\n11/20/2018   5:18:25 AM\nT196\nModule 6 Ł\n Art for Everyone\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\nCorrectionKey=TX-C;NL-B;VA-C\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\nCorrectionKey=TX-C;NL-B;VA-C\n5re_te_06_ts.indd   196\n12/11/2018   8:02:33 AM\nGrade 5 \nTeacher™s Guide\n, Volume 3, Module 6\nBuild Content Knowledge Through  \nMulti-Genre Text Sets\nAuthentic and \naward-winning texts\n build topic knowledge \nexpertise and support reading growth for all students.\nThe selections in each module \npurposefully contribute to \nstudents™ overall content and \ngenre knowledge. \nGuide students to\n interact with \ncomplex texts by annotating\n, taking notes, \nand marking text evidence in \nmy\nBook. \nIntroduce and spark interest in the \nmodule topic\n.\nModel fluent reading\n and promote \nlistening comprehension.\nBuild and \nactivate background \nknowledge\n about the module topic. \nviii\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 'Build Content Knowledge\nInspire inquiry\n and set a purpose for reading. \nLaunch Writing Workshop\n with  high-interest trade books.\nixWelcome to\n HMH Into Reading\nŽDO NOT EDIT--Changes must be made through ﬁFile infoﬂ \nCorrectionKey=NL-B\n',
 '˜\n\n\n\n\n˝\n\n\n\n\n\n\n˚ˆ\n\n\n˝˜\n\n\n\nˆ\n\n\n\n\n\nˆ\n\n\n\n\n\n˛\n\n˝˜\n\n˝\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n˝\n˜\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n˝˜\n\n\n\n\n\n\n\n\n˘\n\n\n\n\n\n\n\n˝š\n\n\n\n\n\n\n˘\n\n\n\n\n\n\n\n˝\n\n\n\n\n\n˝˜\nˆˆ\n\n\n\n\n\n\n\n\n\n˝\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n˝\n11\n12\n13\nhomeland\n \nS\nomeone\n™\ns homeland is \nthe plac\ne wher\ne he or she w\nas bor\nn.\nm\ny\nNo\nt\ne\ns\n62\nDO NO\nT EDIT\n--\nChanges must be made thr\nough \nﬁF\nile inf\no\nﬂ\nC\nor\nr\nec\ntionkey=T\nX\n-\nA\nDO NO\nT EDIT\n--\nChanges must be made thr\nough \nﬁF\nile inf\no\nﬂ\nC\nor\nr\nec\ntionkey=T\nX\n-\nA\n5re_se_m6_phillis.indd   62\n3/8/18   6:39 PM\nGrade 5 \nTeaching Pal\n, Book 2, Module 6\nGrade 5 \nmy\nBook, Book 2, Module 6\nFoster Critical Thinking and  \nDeep Analysis of Text \nmy\nBook\n is a student component that provides \nopportunities for write-in text interactions, such as \nnote-taking, annotating, and responding.\n \nTARGETED CLOSE READ\nDuring subsequent readings, students \nclosely \nanalyze the text\n to apply skills and \ndemonstrate knowledge.\n \n READ FOR UNDERSTANDING\nDuring a first reading of the text, guide students \nto respond to questions, prompts, and \nannotation tips designed to help them \narrive at \nthe gist of the text\n.\nThe companion \nTeaching Pal\n offers \npoint-of-use teacher\n-\ndirected \ninstructional questions and \nprompts that encourage critical \nthinking and deep analysis of the \nmy\nBook student texts. \nx\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',
 '˜˚˛˝\nN\no\ntice\n&\n&\nCritical Thinking and Text Analysis\nDevelop attentive, critical readers using \nthe powerful work of Kylene Beers and \nRobert E. Probst. Notice & Note \nintroduces Signposts and Anchor \nQuestions that help readers understand \nand respond to critical aspects of both \nfiction and nonfiction texts.\nSIGNPOSTS\nSignposts alert readers to significant \nmoments in a text and encourage \nstudents to read closely.\nFiction\nŁ\n \nContrasts & Contradictions\nŁ\n \nWords of the Wiser\nŁ\n \nAha Moment\nŁ\n \nAgain & Again\nŁ\n \nMemory Moment\nŁ\n \nTough Questions\nNonfiction\nŁ\n \nContrasts & Contradictions\nŁ\n \nExtreme or Absolute Language\nŁ\n \nNumbers and Stats\nŁ\n \nQuoted Words\nŁ\n \nWord Gaps\nŁ\n \n3 Big Questions\nUse these notes to help students \ndeepen their understanding\n as \nthey learn to look for signposts in the text in order to create \nmeaning.\n˜˚˛˝\nN\no\ntice\n&\n&\nStrategies for Close Reading\nKylene Beers and Robert E. Probst\nxi\nWelcome to \nHMH Into Reading\nŽ\nDO NOT EDIT--Changes must be made through ﬁFile infoﬂ\n \nCorrectionKey=NL-B\n',

In [3]:
#pagevector_clean_no_periods = []
pagevector_clean = []
page = -1
for pages in pagevector:
        page += 1
        #clean_text = clean.clean(pagevector_lower[page], 
        clean_text = clean(pagevector[page], 
        fix_unicode=True, 
        to_ascii=True, 
        lower=False, 
        no_line_breaks=True,
        no_urls=True, 
        no_numbers=True, 
        no_digits=True, 
        no_currency_symbols=True, 
        no_punct=False, 
        replace_with_punct="", 
        replace_with_url="", 
        replace_with_number="", 
        replace_with_digit="", 
        replace_with_currency_symbol="",
        lang='en')
        pagevector_clean.append(clean_text)

In [4]:
pagevector_clean[0]

'GRADE Teacher™s Guide Volume'

In [5]:
#pagevector_clean[8]

In [6]:
#pagevector_clean[9]

In [7]:
path = "/Users/kazotogbah/Desktop/ResearchDesignForBusinessAnalytics/HMH_box/OneCMS_Learning_Spine_English_Language_Arts2021012117.xlsx" 
skills = pd.io.excel.read_excel(path,skiprows=range(0,4),header=1)
skills

,Level 1: Domain,Level 2: Strand,Level 3: Substrand 1,Level 4: Substrand 2,Level 5: Substrand 3,Skill Title,Skill Description,Skill GUID,Skill Code,Lower Grade,Upper Grade
0,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Identify Intended Audience and Evaluate Its Im...,Identify an informational text's intended audi...,017ab281-a63f-4f41-928e-7d66f29d0bff,CA.GC.1a,K,12
1,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Identify Author's Purpose While Reading Text,Understand that authors write texts for differ...,5d958ee3-826a-444b-89be-047b54923cd0,CA.GC.1b,K,12
2,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Analyze How Author Advances Purpose While Reading,"While reading, analyze how the author advances...",efaa706c-b57a-442e-a9ec-bd4a4fd589d1,CA.GC.1c,K,12
3,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Determine Author's Perspective or Opinions Whi...,Determine the author's perspective and opinion...,015ace30-cf79-4f4e-b973-21bd939a5970,CA.GC.1d,K,12
4,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Evaluate Author's Credibility to Support Readi...,Identify and analyze an author's qualification...,8d26c54f-a2b6-48ef-9aa6-fad26f0475c5,CA.GC.1e,K,12
...,...,...,...,...,...,...,...,...,...,...,...
2289,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Haikus or Tankas,"Write haikus or tankas, following the structur...",e0653513-1af9-493c-99cc-ca26440a59cb,WT.WP.2.C4,K,12
2290,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Riddle Poems,Write riddle poems that require the reader to ...,97410ba5-9fc4-4684-97c4-9be529ceafe5,WT.WP.2.C5,K,12
2291,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Odes,"Write odes to praise people, events, objects, ...",d5d3e7af-d5b5-45f9-8320-77db880d3856,WT.WP.2.C6,K,12
2292,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Sonnets,Write sonnets following the structural charact...,7637f149-07f8-4ca0-84d7-5593e1b9211a,WT.WP.2.C7,K,12
2293,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Free Verse Poems,Write poems in free verse that depart from tra...,d774010e-382b-417f-842b-21dcc46a5a65,WT.WP.2.C8,K,12

In [8]:
#skills_clean=skills_clean.reset_index(drop=True)

In [9]:
#skills_clean

In [10]:
skills["Skill Description"][0]

"Identify an informational text's intended audience while reading, and analyze how it affects the author's development of a text"

---
# abstractive summarization

In [14]:
from transformers import pipeline
import os

In [15]:
summarizer = pipeline("summarization")

In [23]:
## To use the t5-base model for summarization:
summarizer_2 = pipeline("summarization", model="t5-base", 
                      tokenizer="t5-base", framework="tf")

All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-base.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.

In [19]:
text = pagevector_clean[8]

In [20]:
text

'MODULE Welcome to the Module WEEK Genre: Informational Text Lexile® Measure: L Genre: Informational Text my BOOK my BOOK The World Around Us Students view and respond to the video The World Around Us to learn more about different types of artists and art forms. Genre: Informational Text Lexile® Measure: L Guided Reading Level: W READ ALOUD GET CURIOUS VIDEO ~@,".^V^@@ Carefully selected, content-rich text sets help students build topic knowledge and reading skills. READ ALOUD COMMUNICATION READ-ALOUD TEXT What made Andy Warhol a multimedia artist? (A multimedia artist creates many forms~of art; Warhol painted, wrote, made films,~produced music, and published a magazine.) DOK B How did artists in the Pop Art movement want to change art? (They thought the definition of art could be broader; it should be~mass-produced and deal with popular topics.) DOK C Andy Warhol When French leader Napoleon Bonaparte claimed years ago that, fiA good sketch is better than a long speech,fl he was noting the power artists have in a society. The visual arts, such as paintings, photographs, movies, or TV shows, leave an impact that other forms of communication do not. And since these visual arts often reflect the time and place in which they were made, art is a critical part of any society. A Andy Warhol was a very influential modern American artist. In addition to being a painter, Warhol also was a filmmaker, an author, a music producer, and a magazine publisher. His multimedia approach to the visual arts vastly expanded Americans™ awareness of all art. His studio, known as fiThe Factory,fl was a gathering place for New York City™s artists, musicians, and filmmakers. His entrepreneurial styleA he saw himself as a businessman as well as an artistA is a model for many current creative artists. B Warhol is best known as a leader of the Pop Art movement. This group of artists believed that the existing definition of art was too narrow and excluded too many people from appreciating it. At the time, something was~considered art only if it was a unique, one-of-a-kind piece dealing with a~serious subject. Pop artists, however, believed that art could (and should) be~made with recognizable, mass-produced, fipopularfl items that surround~us. C What are some ways art reflects the time and place it is made? (Artists can only use the materials available in their place and time; they learn from other artists who have had similar interests and experiences, etc.) DOK A T Listening Comprehension DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=TX-A my BOOK No matter what form their creations take, all artists have similar goals. Artists explore what it means to be a personA to think, feel, and be. They™re interested in sharing something of themselves as well as provoking emotions in other peopleA their audience. Using a variety of tools, including words, music, paint, and movement, they make people laugh, cry, fear, hope, and wonder. Let™s Get Storytelling People have been using words creatively for many thousands of years. Storytelling began long before people invented writing. Back then, people passed stories along orally. The oldest known written story is a classic tale, The Epic of Gilgamesh , which pays tribute to an honored king. It was first written on clay tablets in the late second or early third millennium B.C.E. Today™s storytellers have many ways to share their work: books, plays, screenplays, magazines, and blogs. Even tweets and text messages can be creative. Writers can use words, letters, and even emojis to communicate ideas. Writers™ stories describe places, people, and events of all kinds. Some are fantastic, such as an interplanetary friendship set in the distant future. Others are more realistic, such as a lonely student struggling to fit in at a new school. Writers often use dialogue to help readers understand characters™ relationships, moods, and motives. CREATIVE ~@,". ^ myNotes DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=TX-A DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=TX-A re_se_m_ma.indd // :: AM my BOOK CHRISTO AND JEANNE-CLAUDE THROUGH THE GATES AND BEYOND JAN GREENBERG AND SANDRA JORDAN myNotes DO NOT EDIT--Changes must be made through fiFile infofl Correctionkey=TX-B;NL-B re_se_m_christo.indd // :: AM T Module L Art for Everyone DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=TX-C;NL-B;VA-C DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=TX-C;NL-B;VA-C re_te__ts.indd // :: AM Grade Teacher™s Guide , Volume , Module Build Content Knowledge Through Multi-Genre Text Sets Authentic and award-winning texts build topic knowledge expertise and support reading growth for all students. The selections in each module purposefully contribute to students™ overall content and genre knowledge. Guide students to interact with complex texts by annotating , taking notes, and marking text evidence in my Book. Introduce and spark interest in the module topic . Model fluent reading and promote listening comprehension. Build and activate background knowledge about the module topic. viii DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=NL-B'

In [33]:
summary_text = summarizer_2(text, max_length=100, min_length=5, 
                          do_sample=False)

In [34]:
summary_text[0]['summary_text']

'art is a critical part of any society because it reflects the time and place in which it was made . students can use words, music, paint, and even emojis to communicate ideas . if you have any questions, please feel free to contact us at cdc@mailto: [email protected]'

In [35]:
summary_page = []
page = -1
for pages in pagevector:
        page += 1 
        clean_text = summarizer_2(pagevector[page],
                               max_length = 100,
                                min_length=5,
                               do_sample =False)[0]['summary_text']
        summary_page.append(clean_text)

Your max_length is set to 100, but you input_length is only 12. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 66. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 93. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 97. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 39. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 39. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 68. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 33. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 32. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 56. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)

Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 100, but you input_length is only 3. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)

In [41]:
summary_page

["GRADE 5 Teacher's Guide Volume 1 .",
 'Authors and Advisors Alma Flor Ada  Kylene Beers  F. Isabel Campoy Joyce Armstrong Carroll  Nathan Clemens Anne Cunningham  Martha C. Hougen Elena Izquierdo  Carol Jago Erik Palmer Robert E. Probst  Shane Templeton  Julie Washington Contributing Consultants David Dockterman  Mindset Works® Jill Eggleton GRADE 5 ',
 'copies of Rubrics and Backmatter pages may not be resold . copies may be photocopied in classroom quantities for instructional use . if you have received these materials as examination copies free of charge, you retain title to the materials .',
 'HMH Into Reading combines the best practices of balanced literacy with comprehensive coverage of English language arts curriculum standards . the authors and consultants who contributed to the program share a deep commitment to education and a passion for learning.',
 'nationally known lecturer on reading and writing with 32 years of classroom experience . author of With Rigor for All and the forthcoming The Book in Question: How and Why Reading Is in Crisis . national and international consultant dedicated to improving literacy, particularly for striving readers .',
 'Into Reading and Arriba la lectura! Alma Flor Ada, Ph.D. Professor Emerita, University of San Francisco . author of over 200 award-winning books, both academic and for young readers . Elena Izquierdo, PhD. Associate Professor of teacher education at the university of Texas .',
 'ANCHOR CHART 17: Central Idea Reading Workshop Students are introduced to skills via Anchor Charts and the shared reading of a common text . a whole-group minilesson is followed by small-group and independent application time .',
 'small-group and independent work 4560 minutes Wrap-Up 5 minutes Reading Workshop viiWelcome to HMH Into Reading!',
 'art is a critical part of any society because it reflects the time and place in which it was made . students can use words, letters, paint, and even emojis to communicate ideas . if you have any questions, please feel free to contact us at cnn.com/artists .',
 'ixWelcome to HMH Into Reading . build Content Knowledge and set a purpose for reading.',
 'my Book is a student component that provides opportunities for write-in text interactions, such as note-taking, annotating, and responding . the companion Teaching Pal offers point-of-use teacher-directed instructional questions and prompts that encourage critical thinking .',
 'Notice & Note introduces Signposts and Anchor Questions that help readers understand and respond to critical aspects of both fiction and nonfiction texts . these notes help students deepen their understanding as they learn to look for signposts in the text to create meaning .',
 'write a two-paragraph personal account telling about a challenge you faced and what it took to overcome that challenge . use evidence from The InventorTMs Secret in your personal account .',
 'Writing Workshop Into Reading employs a writing workshop method of instruction that is student-centered, process-driven, and collaborative . it means teaching writing, not just assigning it .',
 'a dd t o the V ocabular y Net w or k on page 13 b y wr ead synon yms , an t on ymms and phr ases f . a str onauts must tr ansc end a boundar y, y ou go abo v e or be',
 'students will create a safety pamphlet to share with members of your community about natural disasters . students will work in groups to generate ideas, research, complete, and present an inquiry-based project .',
 "HMH's online learning system combines the best of technology, HMH Into Reading content, and instruction to personalize the learning experience for every student .",
 'Your Friend in Learning® is a registered trademark of Houghton Mifflin Harcourt .',
 'data insights help teachers determine a daily skills focus for minilessons and small-group needs . Actionable reports drive grouping, reading, and instructional recommendations appropriate for each learner . data-driven recommendations dynamically assign students to groups, allowing teachers to target learning needs and differentiate instruction .',
 'Adaptive Growth Measure and Guided Reading Benchmark allow teachers to gain an understanding of where students are on the learning continuum . Module Assessments , given every three weeks, assess mastery of skills covered during the course of the module across all literacy strands .',
 ' TeacherTMs Guide  Foundational Skills and Word Study Studio  Tabletop Minilessons: English Language Development  Language Graphic Organizers  Extend Use data to inform which foundational Skills a student is ready to learn beyond where the rest of the class is learning .  Use language supports such as sentence frames and phrase banks to guide effective expression .',
 'ENGLISH LANGUAGE DEVELOPMENT FOUNDATIONAL SKILLS SUPPORT  TeacherTMs Guide  Foundational Skills and Word Study Studio  Tabletop Minilessons: English Language Development . Use language supports such as sentence frames and phrase banks to guide effective expression and empower studentsTM language development .',
 "Into Reading provides resources to help teachers interact with families throughout the school year . the write-in format of my Book gives families a front-row seat to their child's thinking and progress over time .",
 'Professional Learning empowers and supports teachers to be developers of high-impact learning experiences that provide all students with opportunities for reading and writing success .  Getting Started and Professional Learning Guide: Learn the program components, pedagogy, and digital resources to successfully teach with Into Reading .',
 "WH OLE GROUP Teacher's Guide 6 Volumes Teaching Pal 2 Books Writing Workshop TeacherTMs Guide: 1 Volume Anchor Charts my Book: 2 Books Display and Engage Student Materials Teacher Materials ONLINE STUDENT MANAGEMENT CENTER  Access all program materials  Plan lessons  Assign materials .",
 'Professional Learning Guide Guiding Principles and Strategies Foundational Skills and Word Study Studio Take and Teach Lessons: Leveled Readers  Guided Reading Benchmark Assessment Kit Program Assessments:  Adaptive Growth Measure  Reading Remake  Graphic Organizers  Projects and Keyboarding  Read it, Show it Student Choice Library: 6 copies of each title WriterTMs Notebook Tabletop Minilessons: Reading xxv',
 "Inventors change our lives for the better government support of innovation has always benefited society . funding inventors improves people's lives, creates jobs, and helps our nation excel as a leader in science and technology .",
 'a great story can come in many other forms, toomyths and fables, plays, movies, poems, and even songs . books allow readers to use their imaginations. they also allow authors to show more of what characters are thinking than a typical play or film would .',
 'th e sc i n t es a s te r ea rs . ne d eds , na ds, and ni dds. ti rts ! nn dr ts, dns & dmts.',
 'the LOUISIANA TERRITORY was the birthplace of the iroquois . it was the beginning of a new era in the history of the united states . a r i s s is a term used to describe a group of people who migrated to the u.s.',
 'the U.S. government protects Yellowstone national park, formed in 1872, is the first nature preserve created as a national park . a nature preserve is a protected place for plants, animals, and landscapes . it provides important benefits for people as well as for the plants and animals that live there .',
 'Using a variety of tools, including words, music, paint, and movement, artists explore what it means to be a personto think, feel, and be . they make people laugh, cry, fear, hope, and wonder .',
 'this timeline is a chronology of a few of historyTMs daring explorers from the last two centuries . from the top of the world to the bottom of the sea, this timeline includes a selection of the most famous stories from around the world . a couple who explored the northwestern part of the united states in 1804 explored the ocean .',
 'a few survival strategies can help make a big move a lot easier . one way to treat homesickness is by staying in touch with people back home .',
 'fiction detective Sherlock Holmes and the mysteries he solves are a classic form of entertainment . solving mysteries can help us improve our lives, partly because we have a natural instinct for solving puzzles .',
 'scientists regularly study animal behavior around the globe . observing animal behavior helps us understand behaviors that all animals, even humans, have in common .',
 'LA 2/12/18 2. DONE AR 2/12 Footer is Volume 6 . VOLUME 6 Genre Study: Nonfiction Module Overview',
 'xxxvii DO NOT EDIT--Changes must be made through fiFile infofl .',
 'LEVELED LIBRARY Small-Group Reading The Rigby Leveled Library offers a carefully controlled continuum of texts, spanning a range of levels, topics, and genres .',
 'students will listen to, read, and view a variety of texts and media that present them with information about inventors . students will encounter narrative nonfiction, realistic fiction, and science fiction/fantasy .',
 'students will synthesize what they have learned about the topic and make connections to self, society, and other texts . students build deep topic knowledge about innovation, perseverance, and the desire to solve problems .',
 "Inventors at Work Fostering a Learning Mindset . Use the suggestions to weave it throughout students' literacy instruction .",
 'LEARNING MINDSET: Trying Again ACCESS PRIOR KNOWLEDGE/ BUILD BACKGROUND VOCABULARY Big Idea Words  excel  illustrious  revere  transcend MULTIMEDIA Active Listening and Viewing  Get Curious Video: Morning Miracles Build Knowledge and Language Vocabulary Reading Workshop .',
 'Inventors at Work DECODING  Short Vowels  Words with Long a and e  Long i and o FLUENCY  Reading Rate  Accuracy and Self-correction  Phrasing Foundational Skills WRITING PROCESS  Plan and Generate Ideas  Organize, Draft, Revise and Edit Publish and Present .',
 "the federal government must spend more money to support inventors and their work . funding inventors improves people's lives, creates jobs, and helps our nation excel in science and technology .",
 'p_body-question Inventors at Work Genre: Science Fiction/Fantasy Lexile ® Measure: 900L Guided Reading Level: T my BOOK . Essential Question What kinds of circumstances push people to create new inventions?',
 'multiple options allow teachers to tailor instruction based on student need . ENGLISH LANGUAGE DEVELOPMENT Teacher works with small groups to support english language acquisition .',
 "use assessment data and information to group students according to need . Tabletop Minilessons: Reading to scaffold students' understanding of the skill through an Anchor Chart and supporting lesson .  Access online Printables for students to apply their understanding to an independent reading book .",
 'Writing Workshop TeacherTMs Guide provides explicit instruction and ample opportunity for students to write daily . INDEPENDENT WRITING Students work independently to:  generate ideas/ research  draft  write  revise and edit  publish PEER REVIEW Students work in small groups to peer edit . NEEDS-BASED SMALL GROUP Teacher works with small needs-based groups on grammar and writing skills .',
 'True story: today, in living rooms and labs, women are inventing . author: "girls think of everything"',
 "Module MODULE 1 Assessment and Progress Monitoring Ongoing formative assessment guides daily instruction while performance- based assessments demonstrate student progress toward mastery of module skills and standards . Selection Quizzes Assess comprehension of the my Book text selections: weekly assessments assess students' understanding of the key Reading and Writing skills .",
 'use the story map below to plan your narrative . Identify your problem and the obstacles you faced . list in order the steps you took and how you overcame each obstacle . use critical vocabulary words where appropriate .',
 "Use recursive, research-informed instructional routines to support lesson planning and maximize students' learning . Active Viewing Build and extend studentsTM knowledge about a topic by having them actively view and respond to both the Get Curious Videos at the beginning of each module and the videos that appear as selections within the modules . Vocabulary Explicitly teach the meaning of topic - related and academic vocabulary words from the texts .",
 'students will learn about inventors and how their inventions change our lives . take notes and include any questions you have . look for answers when you watch the video again .',
 'students will work in groups to think of an invention and outline a business plan . they will then present their invention and business plan to an audience .',
 'ENGLISH LEARNER SUPPORT: Generate Ideas . students must be able to speak clearly and at a comfortable pace . they must also use gestures and to make eye contact with their audience . a final version of their work should be ready for presentation .',
 'in some stories, the author repeats certain things, such as events, images, or words . a word may be repeated several times, and sometimes it is used in an odd or interesting way .',
 'authors of nonfiction texts often include opposing ideas, or ideas that donTMt agree with something else in the text or between the reader and the text . when authors include words like but , yet, unlike, instead, they are telling the reader that they are describing opposite ideas .',
 "set goals with students and connect with families' to support learning at home . use these ideas to help build your child's knowledge about the topic . Explore the Genre Discuss with your child the characteristics of this genre .",
 "government must spend more money to support inventors and their work . funding inventors improves people's lives, creates jobs, and helps our nation excel . the government spent about $20 billion on the Apollo space program .",
 "this week's Words: excel, illustrious, revere, transcend CRITICAL VOCABULARY: locomotives phonograph incandescent chugged sputtered cylinder gadgets flop patents HIGH-FREQUENCY WORDS famous chief students yourself",
 'T20T21  Introduce the Topic: Inventors at Work  Big Idea Words: excel, illustrious, revere, transcend . T19  Complete Sentences WRITING WORKSHOP Informational Writing, p. T20  Review Critical Vocabulary: locomotives, phonograph, sputtered, flop, incandescent, cylinder, patents, gadget',
 ' Use Printable: Super Six Words to list Big Idea Words and this weekTMs Critical Vocabulary words .  Have students self-select or continue reading an independent reading book .',
 'students should brainstorm ideas and conduct research about an invention . Think about how their research fits into the project plan . write a script for all of the dialogue in your lm . use your thumb to tap the space bar .',
 'the government collects trillions of dollars every year on innovation and invention . funding projects like the Apollo space program helped citizens by creating jobs . failures often lead to success that makes us a world leader .',
 'the InventorTMs Secret by Suzanne Slade and Jennifer Black Reinhardt is a narrative nonfiction text . the text contains a simple theme and is told from a single point of view .',
 'BUILD KNOWLEDGE AND LANGUAGE MODULE LEAD LEARNING OBJECTIVES .',
 'name an invention (e.g., television) and ask students why they think the inventor decided to invent it . discuss the four major reasons for inventing .',
 ' Explain to students that each section of a text can have its own central idea, and that those central ideas tie to the whole textTMs overall main idea . government must fund Inventors is a type of text called a persuasive essay .',
 'use the blue READ FOR UNDERSTANDING prompts to guide discussion of Government Must Fund Inventors as students follow along in their my Book . set a purpose for reading based on the title and headings . engage and respond INDEPENDENT PRACTICE: speaking and listening .',
 'use Tabletop Minilessons: English Language Development card 1.1 to introduce and practice the language skill . use the following text-based prompts with Government Must Fund Inventors to guide application of the skill. use lighter supports to encourage increased language proficiency.',
 'help students identify the central idea by thinking about the title, headings, pictures, charts, and repeated words . english LEARNER SUPPORT Read aloud a section of text supported by a photograph .',
 'Grade 5 Printable DO NOT EDIT--Changes must be made through fiFile infofl . APPLY LANGUAGE SKILL Compare and Contrast Students complete Printable: Language Graphic Organizer 5 .',
 'Central Idea Literacy Centers offer a variety of activities for students . students can use the SOLO CHAIR routine to tell what they learned . they can also use the THINK-PAIR-SHARE routine to share ideas .',
 'use pictures and gestures to ensure students understand each word . challenge students to understand the Blend and Read words that have multiple meanings, such as cast and stub .',
 "a syllable closed with a consonant has a short vowel sound . this means it's pronounced / gr m /, not 'gr n / .",
 'ENGLISH LEARNER SUPPORT: Support Word Meaning ALL LEVELS Make sure students understand the meaning of the spelling words and dictation sentences .',
 'high-frequency words appear often in texts students read . students can learn to recognize them, rather than decode them, so that they can read more fluently .',
 'use the VOCABULARY routine to introduce the Critical Vocabulary . read aloud each word and have students repeat it . have students suggest other examples .',
 'if a vehicle chugged along, how did it move? if someone says their plan turned out to be a flop, how do you think they feel about it?  Would you like to have something incandescent in your bedroom while you sleep? why or why not?',
 'the Teaching Pal prompts in this lesson feature the Notice & Note Signpost: Again and Again .  Discuss the selection, listening actively and making relevant comments .',
 'use the COLLABORATIVE DISCUSSION routine with the questions on Teaching Pal and my Book page 33 . have students annotate their my Book with details from the text and visuals as evidence to explain their responses . ENGLISH LEARNER SUPPORT: Facilitate Discussion Ask students yes/no questions .',
 'use the following text-based prompts with The InventorTMs Secret to guide application of the language skill . Begin with the prompt at the studentTMs identified language proficiency level .',
 " Help students figure out the central idea of a section and restate it in their own words .  Encourage students to use a verb that describes the author's purpose in their summary .",
 'Grade 5 Printable DO NOT EDIT--Changes must be made through fiFile infofl CorrectionKey=NL-A 5re_pr_rgo_04_summarize .',
 'ANCHOR CHART 4: Summarize Wrap-Up Share Time At the end of the Reading Workshop, have students reflect on their learning .',
 'LISTENING COMPREHENSION LESSON 2 COMMUNICATION ENGLISH LEARNER SUPPORT Ask students to draw and label what they just heard about .',
 'Elijah McCoy was the son of slaves who had escaped to Canada on the Underground Railroad . he invented and patented a filubricating cup,fl which allowed oil to drip automatically on the places where it was needed . his invention was so superior that train car manufacturers began to insist on fithe real thing .',
 'the first transcontinental railroad helped invent a new way of talking . railroad workers also used colorful slang to describe their jobs . a distracted person is fiasleep at the switch, figet off the rails, fisee the light at the end of the tunnel .',
 "ENGLISH LEARNER SUPPORT: Build Background Ask students to summarize the significance of McCoy's invention . ask students to tell what they learned so far about inventions .",

In [16]:
#pagevector_clean_no_periods = []
summary_text = []
page = -1
for pages in pagevector:
        page += 1
        summary_text = summarizer(pagevector_clean[page], max_length=100, min_length=5, 
                          do_sample=False)[0]['summary_text']

Your max_length is set to 100, but you input_length is only 9. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Token indices sequence length is longer than the specified maximum sequence length for this model (1200 > 1024). Running this sequence through the model will result in indexing errors

IndexError: index out of range in self

In [ ]:
from transformers import pipeline
import os

# summarizer = pipeline("summarization")

## To use the t5-base model for summarization:
summarizer_2 = pipeline("summarization", model="t5-base", 
                      tokenizer="t5-base", framework="tf")


summary_page = []
page = -1
for pages in pagevector:
        page += 1 
        clean_text = summarizer_2(pagevector[page],
                               max_length = 100,
                                min_length=5,
                               do_sample =False)[0]['summary_text']
        summary_page.append(clean_text)
        
summary_page

---
# Q&A Model

In [11]:
from transformers import BertForQuestionAnswering
#from transformers import AutoModel

In [12]:
model = BertForQuestionAnswering.from_pretrained('deepset/bert-base-cased-squad2')
#model = BertForQuestionAnswering.from_pretrained('deepset/electra-cased-squad2')

In [1]:
from transformers import AutoTokenizer
#from transformers import BertTokenizer

In [2]:
tokenizer = AutoTokenizer.from_pretrained('deepset/bert-base-cased-squad2')

In [48]:
tokenizer.encode(skills["Skill Description"][0],truncation=True,padding=True)

[101,
 146,
 11951,
 6120,
 1126,
 1869,
 1348,
 3087,
 112,
 188,
 3005,
 3703,
 1229,
 3455,
 117,
 1105,
 19774,
 1293,
 1122,
 13974,
 1103,
 2351,
 112,
 188,
 1718,
 1104,
 170,
 3087,
 102]

In [15]:
from transformers import pipeline

In [16]:
nlp = pipeline('question-answering',model =model,tokenizer=tokenizer)

---
# Model Testing with Clean text

In [71]:
nlp({'question':skills["Skill Description"][0],'context':pagevector_clean[8]})['score']

0.11653551459312439

In [55]:
nlp({'question':skills["Skill Description"][0],'context':summary_page[8]})['score']

0.007597899530082941

In [56]:
nlp({'question':skills["Skill Description"][0],'context':summary_page[8]})

{'score': 0.007597899530082941,
 'start': 100,
 'end': 155,
 'answer': 'students can use words, letters, paint, and even emojis'}

In [57]:
nlp({'question':skills["Skill Description"][0],'context':pagevector_clean[8]})

{'score': 0.11653551459312439,
 'start': 4732,
 'end': 4771,
 'answer': 'support reading growth for all students'}

In [18]:
skill_desc=skills["Skill Description"]

In [19]:
skill_desc[2290]

'Write riddle poems that require the reader to guess the subject or the answer to a question'

In [20]:
len(skill_desc)

2294

In [ ]:
range(2294)

In [21]:
import pandas as pd
import numpy as np
qa_scores = []
page = 0
skillnum = 0
for page in range(479):
    page = page+1
    context = pagevector_clean[page]
    score=[]
    for skillnum in range(2293):
        skillnum = skillnum+1
        question = skill_desc[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df = pd.DataFrame(qa_scores)

KeyboardInterrupt:

In [129]:
score_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.006210,0.073971,0.013290,6.903907e-03,0.361027,0.030755,2.201080e-03,0.741377,0.023264,0.044702,0.035437,0.008859,0.064966,0.045288,0.064260
1,0.010955,0.000031,0.000869,1.621703e-04,0.004483,0.009032,2.003684e-04,0.003814,0.000894,0.018680,0.067606,0.002038,0.003611,0.008818,0.003982
2,0.003334,0.009583,0.001146,8.593228e-03,0.003704,0.021509,5.508835e-04,0.019069,0.001267,0.235808,0.056946,0.005245,0.012888,0.066391,0.178514
3,0.002576,0.000334,0.000199,1.133894e-02,0.009549,0.013631,5.262206e-05,0.048090,0.004269,0.080539,0.101629,0.006637,0.027353,0.021109,0.004322
4,0.000357,0.004376,0.000046,1.782551e-03,0.001929,0.000317,1.348799e-05,0.005421,0.000934,0.000546,0.010760,0.000082,0.004899,0.006069,0.016068
5,0.013923,0.000526,0.000017,1.041347e-04,0.000378,0.000009,3.430385e-06,0.001163,0.000149,0.000093,0.013144,0.003599,0.021068,0.023649,0.015215
6,0.001126,0.153144,0.000001,1.164378e-04,0.001253,0.000010,1.160320e-06,0.025341,0.000064,0.000529,0.019029,0.002885,0.024013,0.016817,0.001011
7,0.014380,0.003028,0.002119,2.428939e-03,0.007179,0.000735,4.609771e-04,0.086617,0.013583,0.008776,0.226075,0.009430,0.016130,0.055244,0.029602
8,0.008190,0.006617,0.002677,2.289007e-03,0.013659,0.003117,6.878710e-04,0.029472,0.003009,0.039395,0.000123,0.012817,0.003537,0.007363,0.007804
9,0.002358,0.009046,0.000083,7.026134e-04,0.028119,0.000087,7.515033e-04,0.009497,0.000219,0.003263,0.008282,0.011212,0.001137,0.003140,0.000592
10,0.001058,0.001467,0.000223,1.445041e-04,0.003290,0.000362,2.194143e-04,0.025996,0.005291,0.002053,0.048678,0.218802,0.003216,0.005992,0.002391
11,0.002725,0.005202,0.002209,2.960871e-03,0.040129,0.007506,8.298667e-04,0.151372,0.004983,0.001483,0.009354,0.006529,0.005869,0.009378,0.006911
12,0.001978,0.000712,0.000402,1.972894e-03,0.008621,0.001634,3.518825e-05,0.004823,0.003942,0.001466,0.000160,0.002650,0.014164,0.065821,0.000480
13,0.000330,0.006819,0.000085,6.391741e-03,0.006026,0.000152,2.828534e-06,0.012031,0.000076,0.000418,0.004804,0.000237,0.002663,0.060451,0.001863
14,0.008108,0.009711,0.000261,8.665735e-03,0.099163,0.028602,2.308996e-04,0.019790,0.016599,0.037367,0.081038,0.095713,0.021603,0.026156,0.013344
15,0.003311,0.001230,0.000294,1.300010e-04,0.003982,0.000212,3.367648e-05,0.019940,0.000046,0.045433,0.071108,0.001590,0.003068,0.017191,0.001378
16,0.008745,0.034235,0.011152,7.493390e-02,0.118764,0.020020,9.638232e-03,0.121112,0.030479,0.024812,0.067930,0.030348,0.011947,0.021631,0.037870
17,0.000808,0.001455,0.000010,7.010921e-07,0.004633,0.000055,2.178606e-06,0.014219,0.000242,0.000886,0.607762,0.001759,0.001169,0.012053,0.002317
18,0.001458,0.000292,0.000159,4.617066e-04,0.000746,0.003703,7.791376e-06,0.008039,0.000311,0.002056,0.001451,0.000295,0.002247,0.002867,0.001060
19,0.000997,0.008828,0.000332,2.135554e-03,0.007088,0.009097,1.265318e-04,0.052023,0.000090,0.037558,0.204443,0.002345,0.030928,0.072210,0.056187
20,0.004519,0.015048,0.001621,2.663484e-04,0.019301,0.000191,1.226737e-04,0.005419,0.002098,0.000978,0.038496,0.004025,0.010311,0.022076,0.011659
21,0.000043,0.000889,0.000070,8.875322e-05,0.000682,0.000083,3.769334e-06,0.002928,0.000011,0.001658,0.009985,0.000124,0.000576,0.000570,0.020001
22,0.000177,0.000824,0.000003,2.643764e-05,0.006868,0.000479,7.115160e-07,0.009763,0.000101,0.002840,0.005307,0.001427,0.017798,0.005062,0.000836
23,0.000077,0.000111,0.000071,4.982817e-03,0.000634,0.001586,4.083905e-06,0.001069,0.001471,0.002104,0.008256,0.000155,0.000470,0.000765,0.000172
24,0.000599,0.000034,0.000376,1.116124e-03,0.000955,0.000127,1.857404e-05,0.002608,0.000145,0.006631,0.083341,0.000779,0.002036,0.000953,0.001309
25,0.000311,0.000293,0.001982,6.456448e-04,0.004483,0.015868,2.470950e-05,0.062211,0.000822,0.008242,0.010956,0.000315,0.003263,0.010917,0.016729
26,0.035031,0.001180,0.000107,7.046228e-04,0.097838,0.033288,1.257605e-04,0.387232,0.009379,0.053865,0.041854,0.005121,0.004685,0.019699,0.021579
27,0.001651,0.004783,0.005701,1.693986e-03,0.019096,0.019252,5.330152e-05,0.148037,0.009966,0.126206,0.264421,0.000396,0.058513,0.106142,0.006386
28,0.001205,0.002807,0.000418,4.699600e-04,0.000145,0.005199,3.203649e-04,0.072408,0.000580,0.004691,0.018965,0.002029,0.000516,0.002900,0.024119
29,0.003398,0.000624,0.000881,1.606244e-03,0.020173,0.000901,1.945217e-03,0.111737,0.004980,0.030947,0.042282,0.005532,0.005644,0.005032,0.007437

In [108]:
score_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,0.006210,0.073971,0.013290,0.006904,0.361027,0.030755,0.002201,0.741377,0.023264,0.044702,0.035437,0.008859,0.064966,0.045288,0.064260
1,0.010955,0.000031,0.000869,0.000162,0.004483,0.009032,0.000200,0.003814,0.000894,0.018680,0.067606,0.002038,0.003611,0.008818,0.003982
2,0.003334,0.009583,0.001146,0.008593,0.003704,0.021509,0.000551,0.019069,0.001267,0.235808,0.056946,0.005245,0.012888,0.066391,0.178514
3,0.002576,0.000334,0.000199,0.011339,0.009549,0.013631,0.000053,0.048090,0.004269,0.080539,0.101629,0.006637,0.027353,0.021109,0.004322
4,0.000357,0.004376,0.000046,0.001783,0.001929,0.000317,0.000013,0.005421,0.000934,0.000546,0.010760,0.000082,0.004899,0.006069,0.016068
5,0.013923,0.000526,0.000017,0.000104,0.000378,0.000009,0.000003,0.001163,0.000149,0.000093,0.013144,0.003599,0.021068,0.023649,0.015215
6,0.001126,0.153144,0.000001,0.000116,0.001253,0.000010,0.000001,0.025341,0.000064,0.000529,0.019029,0.002885,0.024013,0.016817,0.001011
7,0.014380,0.003028,0.002119,0.002429,0.007179,0.000735,0.000461,0.086617,0.013583,0.008776,0.226075,0.009430,0.016130,0.055244,0.029602
8,0.008190,0.006617,0.002677,0.002289,0.013659,0.003117,0.000688,0.029472,0.003009,0.039395,0.000123,0.012817,0.003537,0.007363,0.007804
9,0.002358,0.009046,0.000083,0.000703,0.028119,0.000087,0.000752,0.009497,0.000219,0.003263,0.008282,0.011212,0.001137,0.003140,0.000592

In [127]:
import pandas as pd
import numpy as np
qa_scores = []
page = 0
skillnum = 0
for page in range(len(pagevector_clean)):
    page = page+1
    context = pagevector_clean[page]
    score=[]
    for skillnum in range(len(skill_desc)-1):
        skillnum = skillnum+1
        question = skill_desc[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df = pd.DataFrame(qa_scores)

KeyboardInterrupt:

In [ ]:
nlp({'question':"Which skill does this page teaches ?",'context':pagevector_clean[10]})

In [37]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[1]})

{'score': 0.1520404815673828, 'start': 339, 'end': 346, 'answer': 'Changes'}

In [38]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[2]})

{'score': 0.00214632716961205,
 'start': 475,
 'end': 500,
 'answer': 'student™s textbook or kit'}

In [39]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[3]})

{'score': 0.009698246605694294,
 'start': 469,
 'end': 484,
 'answer': 'Maximize Growth'}

In [40]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[4]})

{'score': 0.022213365882635117,
 'start': 2556,
 'end': 2564,
 'answer': 'literacy'}

In [41]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[5]})

{'score': 0.0009743470582179725,
 'start': 17,
 'end': 35,
 'answer': 'AArriba la lectura'}

In [42]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[6]})

{'score': 0.011731872335076332,
 'start': 1287,
 'end': 1301,
 'answer': 'Learn Together'}

In [43]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[7]})

{'score': 0.01583992689847946,
 'start': 785,
 'end': 812,
 'answer': 'heighten reading engagement'}

In [44]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[8]})

{'score': 0.07829277962446213,
 'start': 2896,
 'end': 2948,
 'answer': 'they make people laugh, cry, fear, hope, and wonder.'}

In [45]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[9]})

{'score': 0.013260596431791782, 'start': 32, 'end': 39, 'answer': 'inquiry'}

In [46]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[10]})

{'score': 0.013549817726016045,
 'start': 599,
 'end': 674,
 'answer': 'students closely analyze the text to apply skills and demonstrate knowledge'}

In [47]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[11]})

{'score': 0.029503127560019493,
 'start': 339,
 'end': 407,
 'answer': 'significant moments in a text and encourage students to read closely'}

In [49]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[12]})

{'score': 0.06270595639944077, 'start': 1562, 'end': 1569, 'answer': 'writers'}

In [50]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[13]})

{'score': 0.0001292372908210382,
 'start': 432,
 'end': 468,
 'answer': 'Focal Texts connect to module topics'}

In [51]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[14]})

{'score': 0.016619542613625526,
 'start': 1592,
 'end': 1611,
 'answer': 'personal word banks'}

In [52]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[15]})

{'score': 0.02577565424144268,
 'start': 10506,
 'end': 10581,
 'answer': 'H synthesize information, .B write responses that demonstrate understanding'}

In [53]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[16]})

{'score': 0.004324175883084536,
 'start': 433,
 'end': 486,
 'answer': 'personalize the learning experience for every student'}

In [54]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[17]})

{'score': 0.20870967209339142,
 'start': 86,
 'end': 136,
 'answer': 'View Data and Reports.Use data to Monitor progress'}

In [55]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[18]})

{'score': 0.004480600357055664,
 'start': 0,
 'end': 15,
 'answer': 'Maximize Growth'}

In [56]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[19]})

{'score': 0.0030225871596485376,
 'start': 155,
 'end': 170,
 'answer': 'Adaptive Growth'}

In [57]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[20]})

{'score': 0.04269755631685257,
 'start': 2268,
 'end': 2323,
 'answer': 'understanding of the skill or strategy from whole-group'}

In [58]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[21]})

{'score': 0.0028804473113268614,
 'start': 1805,
 'end': 1826,
 'answer': 'guided reading groups'}

In [59]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[22]})

{'score': 0.007254143711179495,
 'start': 344,
 'end': 358,
 'answer': 'growth mindset'}

In [60]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[23]})

{'score': 0.0021458123810589314, 'start': 610, 'end': 616, 'answer': 'online'}

In [61]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[24]})

{'score': 0.030581053346395493, 'start': 625, 'end': 632, 'answer': 'Changes'}

In [62]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[25]})

{'score': 0.04492434859275818,
 'start': 300,
 'end': 333,
 'answer': 'Data & Reporting: Adaptive Growth'}

In [63]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector_clean[26]})

{'score': 0.002352029550820589,
 'start': 2799,
 'end': 2806,
 'answer': 'Changes'}

---
# Model Testing with less cleaned data

In [64]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector[0]})

{'score': 0.23714777827262878,
 'start': 0,
 'end': 33,
 'answer': 'GRADE 5\nTeacher™s \nGuide\nVolume\n1'}

In [65]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector[1]})

{'score': 0.10048520565032959, 'start': 365, 'end': 372, 'answer': 'Changes'}

In [68]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector[2]})

{'score': 0.0057997144758701324,
 'start': 1576,
 'end': 1616,
 'answer': 'Changes must be made through ﬁFile infoﬂ'}

In [69]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector[3]})

{'score': 0.007827562279999256, 'start': 38, 'end': 47, 'answer': 'Advisors˜'}

In [70]:
nlp({'question':skills_clean["Skill Description"][0],'context':pagevector[10]})

{'score': 0.08966530114412308,
 'start': 818,
 'end': 897,
 'answer': 'students \nclosely \nanalyze the text\n to apply skills and \ndemonstrate knowledge'}

___
# Model with page summary

In [114]:
skill_desc[0]

"Identify an informational text's intended audience while reading, and analyze how it affects the author's development of a text"

In [115]:
summary_page[8]

'art is a critical part of any society because it reflects the time and place in which it was made . students can use words, letters, paint, and even emojis to communicate ideas . if you have any questions, please feel free to contact us at cnn.com/artists .'

In [111]:
nlp({'question':skill_desc[0],'context':summary_page[8]})

{'score': 0.007597899530082941,
 'start': 100,
 'end': 155,
 'answer': 'students can use words, letters, paint, and even emojis'}

In [116]:
summary_page[9]

'ixWelcome to HMH Into Reading . build Content Knowledge and set a purpose for reading.'

In [112]:
nlp({'question':skill_desc[0],'context':summary_page[9]})

{'score': 0.22418929636478424,
 'start': 32,
 'end': 55,
 'answer': 'build Content Knowledge'}

In [117]:
summary_page[10]

'my Book is a student component that provides opportunities for write-in text interactions, such as note-taking, annotating, and responding . the companion Teaching Pal offers point-of-use teacher-directed instructional questions and prompts that encourage critical thinking .'

In [113]:
nlp({'question':skill_desc[0],'context':summary_page[10]})

{'score': 0.012799534946680069,
 'start': 188,
 'end': 275,
 'answer': 'teacher-directed instructional questions and prompts that encourage critical thinking .'}

In [118]:
nlp({'question':skill_desc[0],'context':summary_page[11]})

{'score': 0.018524695187807083,
 'start': 156,
 'end': 208,
 'answer': 'these notes help students deepen their understanding'}

In [119]:
nlp({'question':skill_desc[0],'context':summary_page[12]})

{'score': 0.18234436213970184,
 'start': 121,
 'end': 186,
 'answer': 'use evidence from The InventorTMs Secret in your personal account'}

In [120]:
nlp({'question':skill_desc[0],'context':summary_page[13]})

{'score': 0.03151823580265045,
 'start': 87,
 'end': 103,
 'answer': 'student-centered'}

In [122]:
summary_page[14]

'a dd t o the V ocabular y Net w or k on page 13 b y wr ead synon yms , an t on ymms and phr ases f . a str onauts must tr ansc end a boundar y, y ou go abo v e or be'

In [121]:
nlp({'question':skill_desc[0],'context':summary_page[14]})

{'score': 0.011008800007402897, 'start': 107, 'end': 113, 'answer': 'onauts'}

In [123]:
nlp({'question':skill_desc[0],'context':summary_page[15]})

{'score': 0.1857297271490097,
 'start': 105,
 'end': 133,
 'answer': 'students will work in groups'}

In [124]:
nlp({'question':skill_desc[0],'context':summary_page[16]})

{'score': 0.07689173519611359,
 'start': 62,
 'end': 78,
 'answer': 'HMH Into Reading'}