In [1]:
from sentence_transformers import SentenceTransformer
import operator
import regex as re
from pandas import DataFrame
import numpy as np
import umap
#import hdbscan
import matplotlib.pyplot as plt
import pandas as pd
import PyPDF2
import cleantext
from cleantext import clean

In [2]:
path = "/Users/kazotogbah/Desktop/CapstoneWritting/hmh_data/grade5_teachers_guide_pal_corpus_clean_keywords_sumy_distilroberta34b1dc07f9547647fb90760ba6630e5f92fd7af8e4a0d66a84cc084020f76b2d.pkl" 
teachersGuidePal = pd.read_pickle(path,compression='infer')
teachersGuidePal

,file,page,text,content_type,Skill Title,Skill Description,Skill GUID,Skill Code,strand,strand_description,...,Skill Title_embedded,Skill Description_embedded,strand_embedded,Skill Title_no_periods_embedded,Skill Description_no_periods_embedded,strand_no_periods_embedded,strand_description_no_periods_embedded,skill_description_keywords_embedded,strand_description_keywords_embedded,text_clean_summarized_embedded
0,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,1.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.20862822, -0.033599023, 0.044862866, 0.2881..."
1,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,2.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.16788949, -0.13963626, -0.07024216, 0.53562..."
2,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,3.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.23586863, 0.037411276, 0.0036898185, 0.0774..."
3,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,4.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.13544446, 0.15687963, -0.033667527, -0.0243..."
4,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,5.0,˜\n˚˛˝˙˜\n\nReasons to \nInvent\nSolve \nProbl...,content,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,nan,nan,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,...,"[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.27298772, 0.018115517, 0.27320105, 0.338362..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5577,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write haikus or tankas,write haikus or tankas following the structura...,e0653513-1af9-493c-99cc-ca26440a59cb,WT.WP.2.C4,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.065458834, -0.022467336, -0.14402398, -0.1...","[-0.16295668, -0.059479393, -0.22297119, -0.04...","[0.15197246, -0.00865834, -0.2474561, -0.14950...","[-0.035868734, -0.07316666, -0.20177855, -0.15..."
5578,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write riddle poems,write riddle poems that require the reader to ...,97410ba5-9fc4-4684-97c4-9be529ceafe5,WT.WP.2.C5,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.14212829, -0.087659754, 0.0151685495, -0.1...","[-0.2681789, -0.12879677, 0.017346552, -0.3627...","[0.05806018, 0.06841876, -0.053806134, -0.1370...","[-0.08528366, -0.17463017, -0.021595858, -0.16..."
5579,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write odes,write odes to praise people events objects or ...,d5d3e7af-d5b5-45f9-8320-77db880d3856,WT.WP.2.C6,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.016466925, -0.037565004, 0.065129966, -0.15...","[0.48021975, -0.18707027, -0.0040784995, 0.037...","[0.27416033, 0.013461181, 0.005883138, -0.0807...","[0.05119294, -0.12402764, 0.02975093, -0.16433..."
5580,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write sonnets,write sonnets following the structural charact...,7637f149-07f8-4ca0-84d7-5593e1b9211a,WT.WP.2.C7,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1443302, 0.115797274, 0.0013336517, 0.0579...","[-0.11399182, 0.3713151, -0.121542305, 0.20513...","[0.14028896, 0.2253419, -0.05671437, 0.1401694...","[-0.10235442, 0.053097203, -0.021812407, 0.012..."
5581,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write free verse poems,write poems in free verse that depart from tra...,d774010e-382b-417f-842b-21dcc46a5a65,WT.WP.2.C8,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1202832, 0.020569142, 0.08610445, -0.27497...","[0.1200044, 0.022991914, 0.19192894, -0.269595...","[0.19046833, 0.14302915, -0.020604758, -0.1473...","[-0.047682863, -0.05864437, 0.059854243, -0.29..."

In [3]:
import pandas as pd
import numpy as np
pal_skills = []
pal_content = []
page = -1
for text in teachersGuidePal['content_type']:
    page = page+1
    if teachersGuidePal['content_type'][page]== "content":
        pal_content.append(teachersGuidePal['Skill Description_no_periods_embedded'][page])
    else:
        pal_skills.append(teachersGuidePal['Skill Description_no_periods_embedded'][page])

In [4]:
import pandas as pd
import numpy as np
pal_skills2 = []
pal_content2 = []
page = -1
for text in teachersGuidePal['content_type']:
    page = page+1
    if teachersGuidePal['content_type'][page]== "content":
        pal_content2.append(teachersGuidePal['Skill Description'][page])
    else:
        pal_skills2.append(teachersGuidePal['Skill Description'][page])

In [5]:
import pandas as pd
import numpy as np
skills_to_Quest = []
skillnum = -1
concat_1 = "How to "
concat_2 = "?"
for skill in pal_skills2:
    skillnum = skillnum+1
    skills_to_Quest.append(concat_1 + pal_skills2[skillnum] + concat_2)
    
skills_to_Quest

["How to identify an informational text's intended audience while reading and analyze how it affects the author's development of a text?",
 "How to understand that authors write texts for different purposes to inform persuade entertain or share thoughts or feelings and identify author's purpose(s) while reading text?",
 'How to while reading analyze how the author advances the purpose of a text in terms of style and use of text structure language and rhetoric (e.g. formal or informal language figures of speech tone persuasiveness) and evaluate the degree to which the author achieved the purpose of the text?',
 "How to determine the author's perspective and opinions including underlying values and beliefs based on explicit and implicit information while reading text?",
 "How to identify and analyze an author's qualifications to evaluate the author's credibility?",
 "How to while reading evaluate how an author's personal cultural and historical background impacts their purpose for writing and the structure and meaning of a text?",
 "How to distinguish the author's opinions from one's own opinions while reading text?",
 "How to while reading identify an author's opinions beliefs and attitudes that bias text based on explicit and implicit information from the text or information about the author's background?",
 "How to evaluate how an author's perspective or opinions impact a text while reading?",
 "How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?",
 "How to identify the author's purpose in individual paragraphs or sections of a text?",
 'How to set a purpose for reading text?',
 "How to preview the text to gain information about a text's author genre topic and structure creating a context to inform the text's meaning and significance while reading?",
 'How to make and confirm or refute predictions while reading in order to engage with a text and deepen comprehension?',
 "How to make personal connections between a text and one's own experiences feelings and perspectives to actively read and comprehend deeply?",
 'How to connect a text to what is known about the world and the way things are outside the self to actively read and comprehend deeply?',
 'How to connect information between texts during or after reading to aid with comprehending the new text and to broaden knowledge and gain new perspectives?',
 "How to ask and answer questions while reading to help clarify comprehension deepen understanding of a text's literal meaning and demonstrate comprehension?",
 'How to ask and answer interpretive and evaluative questions while reading to support comprehension and analysis of a text and demonstrate comprehension?',
 'How to visualize situations while reading to develop a deeper understanding and enhance recall of the text?',
 'How to use graphic organizers to aid in comprehension and analysis of text while reading or for later use?',
 'How to use note taking and annotation strategies while reading to monitor comprehension of text or for later use?',
 'How to while reading periodically check for coherence and understanding of main ideas events and concepts?',
 'How to when comprehension breaks down during reading use strategies to adjust such as rereading adjusting reading rate reading ahead summarizing or questioning difficult parts of the text?',
 "How to combine information gained from reading a text with one's own academic and personal knowledge to make inferences about what is not stated directly?",
 'How to distinguish between works of fiction and nonfiction while reading based on text content and features?',
 'How to choose texts for independent reading based on personal preferences of topics authors and genres or reviews or recommendations?',
 'How to access prior knowledge to support comprehension and evaluation of a text while reading?',
 'How to adjust reading style (e.g. skimming re reading close reading) based on purpose for reading?',
 'How to build background knowledge to support comprehension and evaluation of a text while reading?',
 'How to while reading distinguish true realistic and fantastical literary works and elements of literary works?',
 'How to generalize information gained from reading a text to make a prediction about a related situation or text?',
 'How to distinguish between literary and informational texts while reading?',
 'How to evaluate the plausibility of predictions about text based on text evidence while reading?',
 'How to draw conclusions from reading text based on a combination of information from the text and background knowledge to make decisions arrive at opinions or determine results?',
 'How to use a combination of information from text and background knowledge to make valid generalizations about a subject based on reading?',
 'How to cite text details examples and evidence from reading to support inferences conclusions interpretations and arguments?',
 'How to engage in classroom small group or partner conversations about the text during and after reading to build on thoughts and ideas and to deepen understanding of the text?',
 'How to write a response to text after reading to share thoughts feelings ideas or opinions about what was read to aid recall or to deepen comprehension?',
 'How to respond to a text after reading by creating an illustration that recounts events ideas and details about the text?',
 'How to while reading analyze the connections relationships or interactions between individuals ideas or events in a text and explain how they develop throughout the course of the text?',
 'How to while reading compare and contrast works of fiction to works of nonfiction that are about the same or similar topic events or people?',
 "How to while reading analyze how a selection from a text fits into the overall structure of the text and contributes to the text's development?",
 'How to while reading evaluate the degree to which the meaning of a text is clear or ambiguous and the information in a text is consistent or inconsistent and determine the impact on the meaning and significance of the text?',
 'How to evaluate how different mediums present the same text or topic (e.g. books oral performances presentations films) and evaluate similarities and differences in how each medium interprets or represents it?',
 'How to distinguish between an objective summary and a critique or review of text?',
 'How to evaluate summaries of text for accuracy meaning or objectivity?',
 'How to compare and contrast the structure and organization of two or more informational texts while reading?',
 'How to synthesize ideas from reading texts across genres to draw conclusions about the texts and develop knowledge?',
 'How to reflect and respond from a personal perspective (e.g. level of personal enjoyment what was learned agreement/disagreement) after reading text?',
 'How to evaluate the quality and relevance of evidence from text when citing evidence to support inferences conclusions interpretations and arguments?',
 "How to paraphrase texts or parts of texts in one's own words after reading retaining the meaning structure and order of the text?",
 'How to synthesize ideas from different parts within a text while reading to understand how the ideas fit together and contribute to the overall significance of the text?',
 'How to synthesize ideas from written texts with texts read aloud and/or media to draw conclusions and develop knowledge?',
 'How to summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to orally summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to write objective summaries of text after reading providing a shortened version of the text that retains the main points?',
 'How to collaborate to produce writing or media after reading text?',
 "How to understand that graphic features such as illustrations maps or charts contribute to a text's meaning and identify interpret and use graphic features while reading?",
 'How to while reading evaluate the degree to which the graphic features in a text contribute important information that cannot be conveyed by the words alone?',
 'How to understand that text features including chapters headings sub headings and bullets are used to provide organization and visual interest to a text and identify interpret and use text features to locate information while reading text?',
 'How to evaluate the degree to which text features support comprehension while reading text?',
 'How to synthesize information from multiple graphic features to draw conclusions while reading text?',
 'How to understand that information is provided by graphic features and by words and distinguish information that is provided by graphics and by words while reading text?',
 'How to integrate information from text features and/or graphic features to comprehend text while reading?',
 "How to understand that imagery consists of words that appeal to readers' senses and identify imagery while reading text?",
 'How to understand that parallelism is a repetition of grammatically identical words or phrases in a sentence to give it a balance and rhythm and identify parallelism while reading text?',
 "How to while reading text evaluate the degree to which parallelism provides balance and rhythm to a sentence and supports the author's purpose?",
 'How to understand that dialogue is a conversation between two or more characters and identify dialogue while reading text?',
 'How to understand that a dialect is the way a group of people speak a language based on location or background and that authors use dialect to help define characters and identify the use of dialects while reading text?',
 'How to while reading text evaluate the degree to which use of dialects helps define characters?',
 'How to understand that register is the degree of formality in language and identify register while reading text?',
 'How to while reading evaluate the degree to which use of register helps define characters and sets the tone of a work of literature?',
 'How to understand that mood is the emotional atmosphere conveyed by an author and identify the mood of a text while reading?',
 "How to while reading analyze the details that helped create a text's mood and evaluate their effectiveness?",
 "How to understand that tone conveys an author's attitudes and viewpoints toward the topic of the literary work and identify the tone of a text while reading?",
 "How to while reading analyze an author's tone or attitude toward a topic and identify details that communicate the tone?",
 "How to understand that an author's style is the overall voice of the author based on use of language and literary devices to give the work meaning and describe authors' styles while reading?",
 'How to while reading classical and modern works of literature identify and compare and contrast archetypes?',
 'How to while reading classical and modern works of literature identify and compare and contrast motifs?',
 'How to understand that language can be used literally and figuratively and identify literal and figurative uses of language while reading text?',
 "How to while reading analyze the use of figurative language for imagery or rhetorical effect and evaluate its impact on a text and the degree to which it advances the author's purpose?",
 "How to while reading text analyze how use of idioms impacts tone and advances the author's purpose?",
 'How to understand that oxymorons are combinations of words with contrasting meanings and that paradoxes are combinations of self contradictory statements and identify oxymorons and paradoxes while reading?',
 "How to while reading text analyze how use of contradictory language including oxymorons and paradoxes impacts tone and advances the author's purpose in a text?",
 "How to while reading text analyze author's use of literary devices to determine how they impact a text and the degree to which they achieve their purposes?",
 'How to understand that an anecdote is a very short story about an incident that can add meaning interest and informal evidence to a text or dialogue through qualities such as humor inspiration or a personal memory and identify anecdotes while reading text?',
 'How to evaluate the degree to which anecdotes achieve their purpose while reading text?',
 'How to understand that stereotyping is the attribution of a trait or traits to all members of a group rather than treating group members as individuals with many different traits and identify examples of stereotyping while reading text?',
 "How to analyze examples of imagery while reading text to determine which senses they appeal to and the degree to which they add to the reader's experience?",
 "How to while reading text evaluate the degree to which stereotyping impacts the text's development?",
 "How to while reading text analyze an author's use of euphemisms and evaluate how they are used to soften the author's message?",
 "How to understand that euphemisms are words or phrases that are more polite or indirect and used to soften another word or phrase or to neutralize a word's connotation and identify and interpret euphemisms while reading text?",
 "How to while reading text analyze an author's voice or style to understand the author's attitude and evaluate the impact of voice on the meaning the text?",
 "How to while reading text analyze how use of puns impacts tone and advances the author's purpose?",
 'How to understand that sound devices use patterns of sound repetition or words that suggest sounds to impact the meaning and mood of writing and identify sound devices such as assonance consonance alliteration or onomatopoeia while reading text?',
 'How to while reading text evaluate how use of sound devices impacts the meaning and mood of the text and enhances its aesthetic qualities?',
 "How to while reading compare and contrast different authors' use of literary devices to determine how they impact the texts and the degree to which they achieve their purposes?",
 'How to understand that idioms are phrases that have a specific meaning different from their literal meaning and identify idioms while reading text?',
 'How to understand that authors repeat words and phrases for emphasis and identify repetition in while reading text?',
 'How to understand that proverbs and adages are phrases that communicate general truths or advice that go beyond their literal meaning and identify proverbs and adages while reading text?',
 'How to understand that extended metaphors are figurative comparisons developed at length throughout literary works and identify examples of extended metaphors while reading text?',
 'How to while reading text analyze the meaning of extended metaphors and the degree to which they achieve their purpose?',
 'How to understand that similes and metaphors draw comparisons between two different ideas or things but that similes use "like" or "as" to draw the comparison and metaphors do not and identify similes and metaphors while reading text?',
 'How to while reading text analyze the purposes of similes and metaphors and the degree to which they achieve their purposes?',
 'How to understand that analogies use similes and metaphors to compare two very different things and identify analogies while reading text?',
 'How to while reading text analyze the effects that analogies have on the meaning of what they compare?',
 'How to understand that personification attributes human qualities to animals ideas and objects and identify personification while reading text?',
 "How to while reading text analyze examples of personification and evaluate how they affect the readers' perspective of the object of personification?",
 'How to understand that a symbol is an object that represents something else and gives it a special and deeper meaning and identify symbols and interpret what they represent while reading text?',
 "How to while reading text analyze why an author used symbols and how the symbols added to the reader's understanding of the text?",
 'How to understand that allegories are narratives told on literal and symbolic levels in order to communicate about abstract ideas and identify examples of allegories while reading text?',
 'How to while reading text analyze the meanings of the symbolism found in allegories and evaluate their effectiveness in communicating the message of the text?',
 'How to understand that an allusion is a short indirect reference to a person or thing that has a particular significance (e.g. cultural historical) and identify allusions while reading text?',
 'How to evaluate the degree to which an allusion achieves its purpose in a text while reading?',
 'How to understand that irony uses language to convey a message that is different from its literal meaning and identify and interpret irony while reading text?',
 'How to understand the similarities and differences between verbal situational and dramatic irony and identify each type while reading?',
 'How to while reading evaluate the degree to which irony deepens understanding of and adds interest to text?',
 'How to understand that sarcasm uses ironic language to mock insult or convey contempt and identify and interpret sarcasm while reading text?',
 'How to while reading text evaluate the degree to which sarcasm deepens understanding of and adds interest?',
 'How to understand that hyperbole is an extreme exaggeration to emphasize a point or for dramatic effect and identify hyperbole while reading text?',
 "How to while reading text evaluate the degree to which hyperbole emphasizes points and impacts the reader's interest?",
 "How to understand that satire is a device that points out a person's or group's negative qualities by using humor exaggeration and irony for the purpose of exposing those qualities and identify examples of satire while reading?",
 'How to while reading evaluate the degree to which satirical texts achieve their purpose?',
 "How to while reading text evaluate the degree to which an author's word choices are clear accurate and appropriate to convey the author's message effectively?",
 'How to identify the topic that the author addresses in a informational text while reading?',
 'How to identify text level main ideas in informational texts while reading?',
 'How to identify paragraph or section level main ideas in informational text while reading?',
 'How to while reading identify key details that support the main ideas of texts paragraphs or sections of text?',
 'How to identify and analyze conflicting information across two or more informational texts while reading?',
 'How to while reading informational text analyze the development of main ideas and the use of key details to support them?',
 'How to identify paragraph or section level topics in informational texts while reading?',
 'How to while reading evaluate the importance and relevance of key details that support the main ideas of informational texts paragraphs or sections of text?',
 "How to understand that scope is a text's coverage of a topic which can range from narrow (covering few details related to a topic) to broad (covering many details related to a topic) and identify the scope of informational texts while reading?",
 'How to identify individuals ideas concepts or events in informational texts while reading?',
 'How to identify sequential or chronological order of events or steps in a process in informational text while reading using signal words and clues as aids (e.g. now then once already before during after and then and dates [days months years])?',

In [21]:
skills_to_Quest[9]

"How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?"

In [22]:
pal_content2[9]

'mynotes 19 do not edit changes must be made through file infofl correctionkey=tx a 5re_se_m1_inventor.indd 19 2/26/2018 5 40 23 am read for understanding set a purpose have students glance through the images in the inventor s secret. have them describe what is happening in some of the pictures. guide students to set a purpose for reading. discuss with them what they think this selection will be about and what they think they will learn from reading it. dok 2 inventors at work 19 do not edit changes must be made through file infofl correctionkey=tx b nl b'

In [23]:
skills_to_Quest[7]

"How to while reading identify an author's opinions beliefs and attitudes that bias text based on explicit and implicit information from the text or information about the author's background?"

 ---
# Q&A Model

In [6]:
from transformers import BertForQuestionAnswering
#from transformers import AutoModel

In [10]:
model = BertForQuestionAnswering.from_pretrained('distilbert-base-cased-distilled-squad')
#model = BertForQuestionAnswering.from_pretrained('deepset/bert-base-cased-squad2')
#model = BertForQuestionAnswering.from_pretrained('deepset/electra-cased-squad2')

You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.
Some weights of the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing BertForQuestionAnswering: ['distilbert.transformer.layer.3.ffn.lin2.weight', 'distilbert.transformer.layer.5.ffn.lin1.bias', 'distilbert.embeddings.LayerNorm.bias', 'distilbert.transformer.layer.5.attention.q_lin.weight', 'distilbert.transformer.layer.3.attention.v_lin.bias', 'distilbert.transformer.layer.5.attention.out_lin.bias', 'distilbert.transformer.layer.2.attention.q_lin.weight', 'distilbert.transformer.layer.4.attention.k_lin.weight', 'distilbert.transformer.layer.1.sa_layer_norm.bias', 'distilbert.transformer.layer.4.attention.q_lin.weight', 'distilbert.transformer.layer.1.attention.k_lin.weight', 'distilbert.transformer.layer.4.attention.v_lin.bias', 'distilbert.transformer.layer.2.output_layer_norm.weight', 'distilbert.transformer.layer.2.ffn.lin2.weight', 'distilbert.transformer.layer.3.ffn.lin1.weight', 'distilbert.transformer.layer.0.ffn.lin2.weight', 'distilbert.transformer.layer.1.ffn.lin1.bias', 'distilbert.transformer.layer.4.ffn.lin2.weight', 'distilbert.transformer.layer.2.ffn.lin1.weight', 'distilbert.transformer.layer.2.ffn.lin1.bias', 'distilbert.transformer.layer.5.ffn.lin2.bias', 'distilbert.transformer.layer.2.attention.k_lin.weight', 'distilbert.transformer.layer.4.attention.k_lin.bias', 'distilbert.transformer.layer.4.ffn.lin2.bias', 'distilbert.transformer.layer.4.attention.out_lin.bias', 'distilbert.transformer.layer.4.output_layer_norm.weight', 'distilbert.transformer.layer.3.ffn.lin2.bias', 'distilbert.transformer.layer.4.sa_layer_norm.bias', 'distilbert.transformer.layer.4.output_layer_norm.bias', 'distilbert.transformer.layer.1.output_layer_norm.weight', 'distilbert.transformer.layer.3.ffn.lin1.bias', 'distilbert.transformer.layer.5.attention.out_lin.weight', 'distilbert.transformer.layer.4.attention.out_lin.weight', 'distilbert.transformer.layer.5.attention.v_lin.bias', 'distilbert.transformer.layer.2.ffn.lin2.bias', 'distilbert.transformer.layer.1.attention.q_lin.weight', 'distilbert.transformer.layer.4.attention.q_lin.bias', 'distilbert.transformer.layer.5.sa_layer_norm.bias', 'distilbert.transformer.layer.0.attention.q_lin.weight', 'distilbert.transformer.layer.0.sa_layer_norm.bias', 'distilbert.transformer.layer.3.attention.out_lin.weight', 'distilbert.transformer.layer.1.attention.out_lin.bias', 'distilbert.transformer.layer.1.sa_layer_norm.weight', 'distilbert.transformer.layer.2.attention.v_lin.bias', 'distilbert.transformer.layer.3.attention.v_lin.weight', 'distilbert.transformer.layer.2.sa_layer_norm.weight', 'distilbert.transformer.layer.4.attention.v_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.bias', 'distilbert.transformer.layer.1.ffn.lin1.weight', 'distilbert.transformer.layer.0.attention.k_lin.bias', 'distilbert.transformer.layer.0.attention.out_lin.weight', 'distilbert.embeddings.LayerNorm.weight', 'distilbert.transformer.layer.0.output_layer_norm.weight', 'distilbert.embeddings.position_embeddings.weight', 'distilbert.transformer.layer.0.sa_layer_norm.weight', 'distilbert.transformer.layer.5.attention.q_lin.bias', 'distilbert.transformer.layer.2.attention.out_lin.weight', 'distilbert.transformer.layer.5.output_layer_norm.weight', 'distilbert.transformer.layer.0.attention.k_lin.weight', 'distilbert.transformer.layer.5.ffn.lin1.weight', 'distilbert.transformer.layer.3.attention.q_lin.weight', 'distilbert.transformer.layer.1.attention.v_lin.weight', 'distilbert.transformer.layer.2.output_layer_norm.bias', 'distilbert.transformer.layer.3.attention.k_lin.bias', 'distilbert.transformer.layer.3.attention.out_lin.bias', 'distilbert.transformer.layer.3.sa_layer_norm.weight', 'distilbert.transformer.layer.4.sa_layer_norm.weight', 'distilbert.transformer.layer.5.ffn.lin2.weight', 'distilbert.transformer.layer.5.output_layer_norm.bias', 'distilbert.transformer.layer.1.attention.v_lin.bias', 'distilbert.transformer.layer.4.ffn.lin1.weight', 'distilbert.transformer.layer.1.ffn.lin2.bias', 'distilbert.transformer.layer.1.attention.q_lin.bias', 'distilbert.transformer.layer.0.output_layer_norm.bias', 'distilbert.transformer.layer.5.attention.v_lin.weight', 'distilbert.transformer.layer.2.attention.k_lin.bias', 'distilbert.transformer.layer.0.attention.q_lin.bias', 'distilbert.transformer.layer.1.attention.out_lin.weight', 'distilbert.transformer.layer.3.output_layer_norm.weight', 'distilbert.transformer.layer.2.attention.out_lin.bias', 'distilbert.transformer.layer.4.ffn.lin1.bias', 'distilbert.transformer.layer.2.attention.v_lin.weight', 'distilbert.transformer.layer.3.output_layer_norm.bias', 'distilbert.transformer.layer.0.attention.out_lin.bias', 'distilbert.embeddings.word_embeddings.weight', 'distilbert.transformer.layer.1.output_layer_norm.bias', 'distilbert.transformer.layer.0.ffn.lin1.weight', 'distilbert.transformer.layer.5.attention.k_lin.bias', 'distilbert.transformer.layer.3.sa_layer_norm.bias', 'distilbert.transformer.layer.1.attention.k_lin.bias', 'distilbert.transformer.layer.5.attention.k_lin.weight', 'distilbert.transformer.layer.5.sa_layer_norm.weight', 'distilbert.transformer.layer.2.sa_layer_norm.bias', 'distilbert.transformer.layer.3.attention.k_lin.weight', 'distilbert.transformer.layer.1.ffn.lin2.weight', 'distilbert.transformer.layer.3.attention.q_lin.bias', 'distilbert.transformer.layer.2.attention.q_lin.bias', 'distilbert.transformer.layer.0.ffn.lin2.bias', 'distilbert.transformer.layer.0.ffn.lin1.bias']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['encoder.layer.3.attention.self.value.bias', 'encoder.layer.6.attention.self.key.bias', 'encoder.layer.7.output.LayerNorm.bias', 'embeddings.position_embeddings.weight', 'encoder.layer.3.attention.self.query.bias', 'encoder.layer.8.attention.self.query.weight', 'encoder.layer.6.attention.self.value.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.8.output.dense.bias', 'encoder.layer.7.intermediate.dense.weight', 'encoder.layer.5.attention.output.dense.bias', 'encoder.layer.4.attention.output.LayerNorm.bias', 'encoder.layer.9.attention.self.query.weight', 'encoder.layer.8.attention.self.key.bias', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.7.output.LayerNorm.weight', 'embeddings.LayerNorm.bias', 'encoder.layer.10.output.dense.weight', 'encoder.layer.9.output.LayerNorm.weight', 'encoder.layer.1.intermediate.dense.bias', 'encoder.layer.1.attention.self.value.weight', 'encoder.layer.1.output.dense.weight', 'encoder.layer.8.attention.self.key.weight', 'encoder.layer.8.attention.self.value.weight', 'encoder.layer.1.attention.self.query.weight', 'encoder.layer.0.attention.self.query.weight', 'encoder.layer.2.attention.self.query.bias', 'encoder.layer.11.intermediate.dense.weight', 'encoder.layer.0.output.dense.bias', 'encoder.layer.4.output.dense.bias', 'encoder.layer.2.intermediate.dense.weight', 'encoder.layer.3.attention.output.LayerNorm.bias', 'encoder.layer.6.output.dense.bias', 'encoder.layer.7.attention.self.query.weight', 'encoder.layer.9.attention.self.query.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.10.attention.output.dense.weight', 'encoder.layer.11.output.dense.bias', 'encoder.layer.4.intermediate.dense.bias', 'encoder.layer.5.attention.output.dense.weight', 'encoder.layer.0.attention.self.query.bias', 'encoder.layer.10.attention.output.dense.bias', 'encoder.layer.9.attention.output.LayerNorm.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.0.output.dense.weight', 'encoder.layer.6.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.weight', 'encoder.layer.2.intermediate.dense.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.self.key.bias', 'encoder.layer.5.intermediate.dense.bias', 'encoder.layer.8.attention.output.LayerNorm.bias', 'encoder.layer.4.attention.output.LayerNorm.weight', 'encoder.layer.11.output.LayerNorm.bias', 'encoder.layer.11.output.LayerNorm.weight', 'embeddings.token_type_embeddings.weight', 'encoder.layer.1.attention.output.LayerNorm.bias', 'encoder.layer.10.attention.self.query.bias', 'encoder.layer.10.attention.self.value.weight', 'encoder.layer.5.attention.self.value.bias', 'encoder.layer.5.intermediate.dense.weight', 'encoder.layer.11.attention.self.query.weight', 'encoder.layer.0.attention.self.value.bias', 'encoder.layer.2.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.self.value.weight', 'encoder.layer.8.intermediate.dense.weight', 'encoder.layer.4.attention.self.query.bias', 'encoder.layer.10.attention.self.key.weight', 'encoder.layer.2.output.dense.weight', 'encoder.layer.6.attention.output.dense.weight', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.1.attention.output.dense.bias', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.6.intermediate.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.7.attention.output.dense.bias', 'encoder.layer.10.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.self.key.bias', 'encoder.layer.0.attention.output.dense.bias', 'encoder.layer.4.attention.self.key.bias', 'encoder.layer.7.attention.self.value.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.8.attention.self.value.bias', 'encoder.layer.4.intermediate.dense.weight', 'encoder.layer.6.attention.output.dense.bias', 'encoder.layer.5.output.dense.weight', 'encoder.layer.7.attention.self.key.weight', 'encoder.layer.4.output.LayerNorm.weight', 'encoder.layer.3.attention.output.LayerNorm.weight', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.2.output.dense.bias', 'encoder.layer.11.attention.output.dense.weight', 'encoder.layer.9.intermediate.dense.weight', 'encoder.layer.4.output.LayerNorm.bias', 'encoder.layer.2.attention.self.value.bias', 'encoder.layer.8.output.LayerNorm.bias', 'embeddings.LayerNorm.weight', 'encoder.layer.0.attention.output.LayerNorm.bias', 'encoder.layer.5.attention.output.LayerNorm.weight', 'encoder.layer.1.attention.output.dense.weight', 'encoder.layer.7.intermediate.dense.bias', 'encoder.layer.9.attention.output.dense.bias', 'encoder.layer.8.attention.output.LayerNorm.weight', 'encoder.layer.8.attention.self.query.bias', 'encoder.layer.0.output.LayerNorm.weight', 'encoder.layer.6.attention.self.query.weight', 'encoder.layer.10.output.LayerNorm.bias', 'encoder.layer.11.intermediate.dense.bias', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.2.attention.self.key.bias', 'encoder.layer.2.output.LayerNorm.weight', 'encoder.layer.3.intermediate.dense.bias', 'encoder.layer.3.attention.self.query.weight', 'embeddings.word_embeddings.weight', 'encoder.layer.3.output.LayerNorm.weight', 'encoder.layer.3.attention.self.key.weight', 'encoder.layer.6.output.dense.weight', 'encoder.layer.3.output.LayerNorm.bias', 'encoder.layer.10.intermediate.dense.bias', 'encoder.layer.11.attention.self.value.weight', 'encoder.layer.9.attention.self.value.weight', 'encoder.layer.0.intermediate.dense.bias', 'encoder.layer.1.attention.self.value.bias', 'encoder.layer.5.output.dense.bias', 'encoder.layer.9.intermediate.dense.bias', 'encoder.layer.11.attention.self.query.bias', 'encoder.layer.9.output.dense.bias', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.2.attention.self.key.weight', 'encoder.layer.0.output.LayerNorm.bias', 'encoder.layer.6.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.output.dense.weight', 'encoder.layer.5.attention.self.query.weight', 'encoder.layer.1.output.dense.bias', 'encoder.layer.6.output.LayerNorm.bias', 'encoder.layer.7.attention.self.query.bias', 'encoder.layer.8.output.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.11.attention.output.LayerNorm.weight', 'encoder.layer.0.attention.self.key.weight', 'encoder.layer.4.attention.output.dense.weight', 'encoder.layer.4.attention.self.key.weight', 'encoder.layer.10.attention.output.LayerNorm.bias', 'encoder.layer.5.output.LayerNorm.weight', 'encoder.layer.1.output.LayerNorm.weight', 'encoder.layer.10.attention.self.key.bias', 'encoder.layer.3.intermediate.dense.weight', 'encoder.layer.5.output.LayerNorm.bias', 'encoder.layer.2.attention.self.value.weight', 'encoder.layer.0.attention.self.value.weight', 'encoder.layer.2.output.LayerNorm.bias', 'encoder.layer.6.attention.output.LayerNorm.bias', 'encoder.layer.7.attention.self.key.bias', 'encoder.layer.5.attention.self.query.bias', 'encoder.layer.5.attention.self.key.bias', 'encoder.layer.0.attention.output.LayerNorm.weight', 'encoder.layer.7.output.dense.weight', 'encoder.layer.0.attention.self.key.bias', 'encoder.layer.10.output.dense.bias', 'encoder.layer.1.output.LayerNorm.bias', 'encoder.layer.4.attention.self.value.bias', 'encoder.layer.11.attention.self.key.bias', 'encoder.layer.6.output.LayerNorm.weight', 'encoder.layer.2.attention.output.dense.bias', 'encoder.layer.4.attention.self.value.weight', 'encoder.layer.3.output.dense.weight', 'encoder.layer.5.attention.output.LayerNorm.bias', 'encoder.layer.8.attention.output.dense.weight', 'encoder.layer.9.attention.self.value.bias', 'encoder.layer.3.attention.output.dense.bias', 'encoder.layer.4.attention.self.query.weight', 'encoder.layer.7.attention.output.dense.weight', 'encoder.layer.6.intermediate.dense.bias', 'encoder.layer.6.attention.self.key.weight', 'encoder.layer.8.attention.output.dense.bias', 'encoder.layer.1.attention.self.key.weight', 'encoder.layer.10.attention.self.value.bias', 'encoder.layer.11.output.dense.weight', 'encoder.layer.6.attention.self.value.bias', 'encoder.layer.11.attention.self.value.bias', 'encoder.layer.8.intermediate.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.9.attention.self.key.weight', 'encoder.layer.10.attention.self.query.weight', 'encoder.layer.4.attention.output.dense.bias', 'encoder.layer.7.attention.self.value.weight', 'encoder.layer.11.attention.output.LayerNorm.bias', 'encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.11.attention.self.key.weight', 'encoder.layer.0.attention.output.dense.weight', 'encoder.layer.2.attention.output.dense.weight', 'encoder.layer.1.intermediate.dense.weight', 'encoder.layer.9.output.LayerNorm.bias', 'encoder.layer.9.attention.output.LayerNorm.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.4.output.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
"""
You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.
Some weights of the model checkpoint at distilbert-base-cased-distilled-squad were not used when initializing BertForQuestionAnswering: ['distilbert.transformer.layer.3.ffn.lin2.weight', 'distilbert.transformer.layer.5.ffn.lin1.bias', 'distilbert.embeddings.LayerNorm.bias', 'distilbert.transformer.layer.5.attention.q_lin.weight', 'distilbert.transformer.layer.3.attention.v_lin.bias', 'distilbert.transformer.layer.5.attention.out_lin.bias', 'distilbert.transformer.layer.2.attention.q_lin.weight', 'distilbert.transformer.layer.4.attention.k_lin.weight', 'distilbert.transformer.layer.1.sa_layer_norm.bias', 'distilbert.transformer.layer.4.attention.q_lin.weight', 'distilbert.transformer.layer.1.attention.k_lin.weight', 'distilbert.transformer.layer.4.attention.v_lin.bias', 'distilbert.transformer.layer.2.output_layer_norm.weight', 'distilbert.transformer.layer.2.ffn.lin2.weight', 'distilbert.transformer.layer.3.ffn.lin1.weight', 'distilbert.transformer.layer.0.ffn.lin2.weight', 'distilbert.transformer.layer.1.ffn.lin1.bias', 'distilbert.transformer.layer.4.ffn.lin2.weight', 'distilbert.transformer.layer.2.ffn.lin1.weight', 'distilbert.transformer.layer.2.ffn.lin1.bias', 'distilbert.transformer.layer.5.ffn.lin2.bias', 'distilbert.transformer.layer.2.attention.k_lin.weight', 'distilbert.transformer.layer.4.attention.k_lin.bias', 'distilbert.transformer.layer.4.ffn.lin2.bias', 'distilbert.transformer.layer.4.attention.out_lin.bias', 'distilbert.transformer.layer.4.output_layer_norm.weight', 'distilbert.transformer.layer.3.ffn.lin2.bias', 'distilbert.transformer.layer.4.sa_layer_norm.bias', 'distilbert.transformer.layer.4.output_layer_norm.bias', 'distilbert.transformer.layer.1.output_layer_norm.weight', 'distilbert.transformer.layer.3.ffn.lin1.bias', 'distilbert.transformer.layer.5.attention.out_lin.weight', 'distilbert.transformer.layer.4.attention.out_lin.weight', 'distilbert.transformer.layer.5.attention.v_lin.bias', 'distilbert.transformer.layer.2.ffn.lin2.bias', 'distilbert.transformer.layer.1.attention.q_lin.weight', 'distilbert.transformer.layer.4.attention.q_lin.bias', 'distilbert.transformer.layer.5.sa_layer_norm.bias', 'distilbert.transformer.layer.0.attention.q_lin.weight', 'distilbert.transformer.layer.0.sa_layer_norm.bias', 'distilbert.transformer.layer.3.attention.out_lin.weight', 'distilbert.transformer.layer.1.attention.out_lin.bias', 'distilbert.transformer.layer.1.sa_layer_norm.weight', 'distilbert.transformer.layer.2.attention.v_lin.bias', 'distilbert.transformer.layer.3.attention.v_lin.weight', 'distilbert.transformer.layer.2.sa_layer_norm.weight', 'distilbert.transformer.layer.4.attention.v_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.weight', 'distilbert.transformer.layer.0.attention.v_lin.bias', 'distilbert.transformer.layer.1.ffn.lin1.weight', 'distilbert.transformer.layer.0.attention.k_lin.bias', 'distilbert.transformer.layer.0.attention.out_lin.weight', 'distilbert.embeddings.LayerNorm.weight', 'distilbert.transformer.layer.0.output_layer_norm.weight', 'distilbert.embeddings.position_embeddings.weight', 'distilbert.transformer.layer.0.sa_layer_norm.weight', 'distilbert.transformer.layer.5.attention.q_lin.bias', 'distilbert.transformer.layer.2.attention.out_lin.weight', 'distilbert.transformer.layer.5.output_layer_norm.weight', 'distilbert.transformer.layer.0.attention.k_lin.weight', 'distilbert.transformer.layer.5.ffn.lin1.weight', 'distilbert.transformer.layer.3.attention.q_lin.weight', 'distilbert.transformer.layer.1.attention.v_lin.weight', 'distilbert.transformer.layer.2.output_layer_norm.bias', 'distilbert.transformer.layer.3.attention.k_lin.bias', 'distilbert.transformer.layer.3.attention.out_lin.bias', 'distilbert.transformer.layer.3.sa_layer_norm.weight', 'distilbert.transformer.layer.4.sa_layer_norm.weight', 'distilbert.transformer.layer.5.ffn.lin2.weight', 'distilbert.transformer.layer.5.output_layer_norm.bias', 'distilbert.transformer.layer.1.attention.v_lin.bias', 'distilbert.transformer.layer.4.ffn.lin1.weight', 'distilbert.transformer.layer.1.ffn.lin2.bias', 'distilbert.transformer.layer.1.attention.q_lin.bias', 'distilbert.transformer.layer.0.output_layer_norm.bias', 'distilbert.transformer.layer.5.attention.v_lin.weight', 'distilbert.transformer.layer.2.attention.k_lin.bias', 'distilbert.transformer.layer.0.attention.q_lin.bias', 'distilbert.transformer.layer.1.attention.out_lin.weight', 'distilbert.transformer.layer.3.output_layer_norm.weight', 'distilbert.transformer.layer.2.attention.out_lin.bias', 'distilbert.transformer.layer.4.ffn.lin1.bias', 'distilbert.transformer.layer.2.attention.v_lin.weight', 'distilbert.transformer.layer.3.output_layer_norm.bias', 'distilbert.transformer.layer.0.attention.out_lin.bias', 'distilbert.embeddings.word_embeddings.weight', 'distilbert.transformer.layer.1.output_layer_norm.bias', 'distilbert.transformer.layer.0.ffn.lin1.weight', 'distilbert.transformer.layer.5.attention.k_lin.bias', 'distilbert.transformer.layer.3.sa_layer_norm.bias', 'distilbert.transformer.layer.1.attention.k_lin.bias', 'distilbert.transformer.layer.5.attention.k_lin.weight', 'distilbert.transformer.layer.5.sa_layer_norm.weight', 'distilbert.transformer.layer.2.sa_layer_norm.bias', 'distilbert.transformer.layer.3.attention.k_lin.weight', 'distilbert.transformer.layer.1.ffn.lin2.weight', 'distilbert.transformer.layer.3.attention.q_lin.bias', 'distilbert.transformer.layer.2.attention.q_lin.bias', 'distilbert.transformer.layer.0.ffn.lin2.bias', 'distilbert.transformer.layer.0.ffn.lin1.bias']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-cased-distilled-squad and are newly initialized: ['encoder.layer.3.attention.self.value.bias', 'encoder.layer.6.attention.self.key.bias', 'encoder.layer.7.output.LayerNorm.bias', 'embeddings.position_embeddings.weight', 'encoder.layer.3.attention.self.query.bias', 'encoder.layer.8.attention.self.query.weight', 'encoder.layer.6.attention.self.value.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.8.output.dense.bias', 'encoder.layer.7.intermediate.dense.weight', 'encoder.layer.5.attention.output.dense.bias', 'encoder.layer.4.attention.output.LayerNorm.bias', 'encoder.layer.9.attention.self.query.weight', 'encoder.layer.8.attention.self.key.bias', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.7.output.LayerNorm.weight', 'embeddings.LayerNorm.bias', 'encoder.layer.10.output.dense.weight', 'encoder.layer.9.output.LayerNorm.weight', 'encoder.layer.1.intermediate.dense.bias', 'encoder.layer.1.attention.self.value.weight', 'encoder.layer.1.output.dense.weight', 'encoder.layer.8.attention.self.key.weight', 'encoder.layer.8.attention.self.value.weight', 'encoder.layer.1.attention.self.query.weight', 'encoder.layer.0.attention.self.query.weight', 'encoder.layer.2.attention.self.query.bias', 'encoder.layer.11.intermediate.dense.weight', 'encoder.layer.0.output.dense.bias', 'encoder.layer.4.output.dense.bias', 'encoder.layer.2.intermediate.dense.weight', 'encoder.layer.3.attention.output.LayerNorm.bias', 'encoder.layer.6.output.dense.bias', 'encoder.layer.7.attention.self.query.weight', 'encoder.layer.9.attention.self.query.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.10.attention.output.dense.weight', 'encoder.layer.11.output.dense.bias', 'encoder.layer.4.intermediate.dense.bias', 'encoder.layer.5.attention.output.dense.weight', 'encoder.layer.0.attention.self.query.bias', 'encoder.layer.10.attention.output.dense.bias', 'encoder.layer.9.attention.output.LayerNorm.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.0.output.dense.weight', 'encoder.layer.6.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.weight', 'encoder.layer.2.intermediate.dense.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.self.key.bias', 'encoder.layer.5.intermediate.dense.bias', 'encoder.layer.8.attention.output.LayerNorm.bias', 'encoder.layer.4.attention.output.LayerNorm.weight', 'encoder.layer.11.output.LayerNorm.bias', 'encoder.layer.11.output.LayerNorm.weight', 'embeddings.token_type_embeddings.weight', 'encoder.layer.1.attention.output.LayerNorm.bias', 'encoder.layer.10.attention.self.query.bias', 'encoder.layer.10.attention.self.value.weight', 'encoder.layer.5.attention.self.value.bias', 'encoder.layer.5.intermediate.dense.weight', 'encoder.layer.11.attention.self.query.weight', 'encoder.layer.0.attention.self.value.bias', 'encoder.layer.2.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.self.value.weight', 'encoder.layer.8.intermediate.dense.weight', 'encoder.layer.4.attention.self.query.bias', 'encoder.layer.10.attention.self.key.weight', 'encoder.layer.2.output.dense.weight', 'encoder.layer.6.attention.output.dense.weight', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.1.attention.output.dense.bias', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.6.intermediate.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.7.attention.output.dense.bias', 'encoder.layer.10.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.self.key.bias', 'encoder.layer.0.attention.output.dense.bias', 'encoder.layer.4.attention.self.key.bias', 'encoder.layer.7.attention.self.value.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.8.attention.self.value.bias', 'encoder.layer.4.intermediate.dense.weight', 'encoder.layer.6.attention.output.dense.bias', 'encoder.layer.5.output.dense.weight', 'encoder.layer.7.attention.self.key.weight', 'encoder.layer.4.output.LayerNorm.weight', 'encoder.layer.3.attention.output.LayerNorm.weight', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.2.output.dense.bias', 'encoder.layer.11.attention.output.dense.weight', 'encoder.layer.9.intermediate.dense.weight', 'encoder.layer.4.output.LayerNorm.bias', 'encoder.layer.2.attention.self.value.bias', 'encoder.layer.8.output.LayerNorm.bias', 'embeddings.LayerNorm.weight', 'encoder.layer.0.attention.output.LayerNorm.bias', 'encoder.layer.5.attention.output.LayerNorm.weight', 'encoder.layer.1.attention.output.dense.weight', 'encoder.layer.7.intermediate.dense.bias', 'encoder.layer.9.attention.output.dense.bias', 'encoder.layer.8.attention.output.LayerNorm.weight', 'encoder.layer.8.attention.self.query.bias', 'encoder.layer.0.output.LayerNorm.weight', 'encoder.layer.6.attention.self.query.weight', 'encoder.layer.10.output.LayerNorm.bias', 'encoder.layer.11.intermediate.dense.bias', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.2.attention.self.key.bias', 'encoder.layer.2.output.LayerNorm.weight', 'encoder.layer.3.intermediate.dense.bias', 'encoder.layer.3.attention.self.query.weight', 'embeddings.word_embeddings.weight', 'encoder.layer.3.output.LayerNorm.weight', 'encoder.layer.3.attention.self.key.weight', 'encoder.layer.6.output.dense.weight', 'encoder.layer.3.output.LayerNorm.bias', 'encoder.layer.10.intermediate.dense.bias', 'encoder.layer.11.attention.self.value.weight', 'encoder.layer.9.attention.self.value.weight', 'encoder.layer.0.intermediate.dense.bias', 'encoder.layer.1.attention.self.value.bias', 'encoder.layer.5.output.dense.bias', 'encoder.layer.9.intermediate.dense.bias', 'encoder.layer.11.attention.self.query.bias', 'encoder.layer.9.output.dense.bias', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.2.attention.self.key.weight', 'encoder.layer.0.output.LayerNorm.bias', 'encoder.layer.6.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.output.dense.weight', 'encoder.layer.5.attention.self.query.weight', 'encoder.layer.1.output.dense.bias', 'encoder.layer.6.output.LayerNorm.bias', 'encoder.layer.7.attention.self.query.bias', 'encoder.layer.8.output.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.11.attention.output.LayerNorm.weight', 'encoder.layer.0.attention.self.key.weight', 'encoder.layer.4.attention.output.dense.weight', 'encoder.layer.4.attention.self.key.weight', 'encoder.layer.10.attention.output.LayerNorm.bias', 'encoder.layer.5.output.LayerNorm.weight', 'encoder.layer.1.output.LayerNorm.weight', 'encoder.layer.10.attention.self.key.bias', 'encoder.layer.3.intermediate.dense.weight', 'encoder.layer.5.output.LayerNorm.bias', 'encoder.layer.2.attention.self.value.weight', 'encoder.layer.0.attention.self.value.weight', 'encoder.layer.2.output.LayerNorm.bias', 'encoder.layer.6.attention.output.LayerNorm.bias', 'encoder.layer.7.attention.self.key.bias', 'encoder.layer.5.attention.self.query.bias', 'encoder.layer.5.attention.self.key.bias', 'encoder.layer.0.attention.output.LayerNorm.weight', 'encoder.layer.7.output.dense.weight', 'encoder.layer.0.attention.self.key.bias', 'encoder.layer.10.output.dense.bias', 'encoder.layer.1.output.LayerNorm.bias', 'encoder.layer.4.attention.self.value.bias', 'encoder.layer.11.attention.self.key.bias', 'encoder.layer.6.output.LayerNorm.weight', 'encoder.layer.2.attention.output.dense.bias', 'encoder.layer.4.attention.self.value.weight', 'encoder.layer.3.output.dense.weight', 'encoder.layer.5.attention.output.LayerNorm.bias', 'encoder.layer.8.attention.output.dense.weight', 'encoder.layer.9.attention.self.value.bias', 'encoder.layer.3.attention.output.dense.bias', 'encoder.layer.4.attention.self.query.weight', 'encoder.layer.7.attention.output.dense.weight', 'encoder.layer.6.intermediate.dense.bias', 'encoder.layer.6.attention.self.key.weight', 'encoder.layer.8.attention.output.dense.bias', 'encoder.layer.1.attention.self.key.weight', 'encoder.layer.10.attention.self.value.bias', 'encoder.layer.11.output.dense.weight', 'encoder.layer.6.attention.self.value.bias', 'encoder.layer.11.attention.self.value.bias', 'encoder.layer.8.intermediate.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.9.attention.self.key.weight', 'encoder.layer.10.attention.self.query.weight', 'encoder.layer.4.attention.output.dense.bias', 'encoder.layer.7.attention.self.value.weight', 'encoder.layer.11.attention.output.LayerNorm.bias', 'encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.11.attention.self.key.weight', 'encoder.layer.0.attention.output.dense.weight', 'encoder.layer.2.attention.output.dense.weight', 'encoder.layer.1.intermediate.dense.weight', 'encoder.layer.9.output.LayerNorm.bias', 'encoder.layer.9.attention.output.LayerNorm.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.4.output.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
"""

In [11]:
from transformers import AutoTokenizer
#from transformers import BertTokenizer

In [12]:
tokenizer = AutoTokenizer.from_pretrained('deepset/bert-base-cased-squad2')
#tokenizer.encode(skills["Skill Description"][0],truncation=True,padding=True)

In [13]:
from transformers import pipeline 
distil_bert_qa = pipeline('question-answering',model =model,tokenizer=tokenizer)

In [11]:
#distilqa = pipeline('question-answering', model='distilbert-base-cased-distilled-squad', tokenizer='bert-base-cased')

Downloading:   0%|          | 0.00/473 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/261M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

In [19]:
pal_content2[0]

"module i will not follow where the path may lead but i will go where there is no path and i will leave a trail.fl smuriel strode inventors at work inventors at work 10 do not edit changes must be made through file infofl correctionkey=tx a do not edit changes must be made through file infofl correctionkey=tx a 5re_se_m1_mo.indd 10 2/26/2018 5 35 52 am what kinds of circumstances push people to create new inventions? 11 do not edit changes must be made through file infofl correctionkey=tx b nl b 5re_se_m1_mo.indd 11 11/2/2018 12 53 07 am introduce the topic read aloud the module title inventors at work. tell students that in this module they will be reading and viewing selections on the topic of inventors. have students brainstorm famous inventors and share what they know about their inventions. then ask students to discuss the module title and explain the different types of work inventors may do to come up with an invention that works. (possible responses inventors do a lot of research. they also have to test out their ideas and problem solve when something doesn t work.) discuss the quotation read aloud the quotation by muriel strode. lead a discussion in which students discuss whether they agree with strode's statement and why. explain the meaning of the quote as needed inventors strive to discover new paths or new ways of doing things. give examples of recent inventions that have made our lives better. (accept reasonable responses.) 10 module 1 do not edit changes must be made through file infofl correctionkey=tx b nl b"

In [20]:
skills_to_Quest[0]

"How to identify an informational text's intended audience while reading and analyze how it affects the author's development of a text?"

In [14]:
distil_bert_qa({'context':pal_content2[0],'question':skills_to_Quest[0]})

{'score': 0.00021314233890734613,
 'start': 920,
 'end': 991,
 'answer': 'with an invention that works. (possible responses inventors do a lot of'}

In [15]:
import pandas as pd
import numpy as np
page = 0
skillnum = 0
qa_scores = []
for page in range(0,10):
    page =page+1
    context = pal_content2[page]
    score=[]
    for skillnum in range(0,10):
        question = skills_to_Quest[skillnum]
        skillnum =skillnum+1
        score.append(distil_bert_qa({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df_clean_text_distil = pd.DataFrame(qa_scores)

In [16]:
score_df_clean_text_distil

,0,1,2,3,4,5,6,7,8,9
0,0.000096,0.000092,0.000078,0.000062,0.000069,0.000066,0.000068,0.000078,0.000073,0.000092
1,0.000110,0.000087,0.000089,0.000105,0.000167,0.000151,0.000166,0.000108,0.000113,0.000088
2,0.000180,0.000150,0.000139,0.000162,0.000208,0.000150,0.000207,0.000185,0.000229,0.000151
3,0.000094,0.000103,0.000085,0.000106,0.000096,0.000101,0.000096,0.000087,0.000081,0.000103
4,0.000195,0.000209,0.000222,0.000292,0.000260,0.000261,0.000258,0.000194,0.000224,0.000209
5,0.000067,0.000068,0.000171,0.000055,0.000080,0.000054,0.000079,0.000056,0.000080,0.000069
6,0.000109,0.000114,0.000079,0.000096,0.000119,0.000082,0.000119,0.000083,0.000117,0.000115
7,0.000044,0.000039,0.000244,0.000049,0.000058,0.000045,0.000058,0.000059,0.000056,0.000039
8,0.000249,0.000338,0.000234,0.000278,0.000241,0.000201,0.000241,0.000190,0.000278,0.000339
9,0.000061,0.000053,0.000204,0.000045,0.000046,0.000052,0.000046,0.000048,0.000061,0.000052

In [17]:
import pandas as pd
import numpy as np
page = 0
skillnum = 0
qa_scores = []
for page in range(0,10):
    page =page+1
    context = pal_content2[page]
    score=[]
    for skillnum in range(0,10):
        question = skills_to_Quest[skillnum]
        skillnum =skillnum+1
        score.append(distil_bert_qa({'context':context,'question':question})['answer'])
    qa_scores.append(score)
        
        
score_df_clean_text_distil_text = pd.DataFrame(qa_scores)

In [18]:
score_df_clean_text_distil_text

,0,1,2,3,4,5,6,7,8,9
0,circumstances push people to create new invent...,52 am what kinds of,circumstances push people to create new invent...,_m1_mo.indd 11 11/,a 5re_se_m1_mo,aloud the,a 5re_se_m1_mo,52 am what kinds of,"circumstances in this context (""the",52 am what kinds of
1,spanish cognate. illustrious ilustre 12 module 1,use the vocabulary routine and,tx,vocabulary routine and the vocabulary cards to...,2018 5 36 46 am big idea words use the,vocabulary cards to introduce the,2018 5 36 46 am big idea words use the,english,illustrious,use the vocabulary routine and
2,a 5re_se_m1_bi,network. remind students to come,tx,they decide what to add to the,correctionkey=,word relates to inventors,correctionkey=,network,tx,network. remind students to come
3,details to the map. at the end of the,tx,correctionkey=,indd 15 2/,correctionkey=,to review the texts,correctionkey=,36 30 am knowledge map review the categories o...,not edit changes must be made through file infofl,tx
4,tx,be made through file infofl correctionkey=,correctionkey=,indd 15 2/,correctionkey=,2018 5 36 29 am make life easier entertain,correctionkey=,tx a 5re_se_m1_km.indd,not edit changes must be made through file infofl,be made through file infofl correctionkey=
5,) where is the central,6 7 8,support the central idea? (by sharing examples...,central,) where is the central idea stated? (the,support truly great innovation. to build a faster,) where is the central idea stated? (the,support truly great innovation. to build a faster,central idea stated? (the last sentence of the,6 7 8
6,6 7 8 9 10 11,6 7 8,dok 3 read for understanding central idea how ...,it supports improvements to the,in the text,become stronger and more of a world leader,in the text,dok 3 inventors at,? (inventors can help make the,6 7 8
7,genre information. have students discuss the,way helps readers understand what happened and...,text read aloud and discuss the genre informat...,genre of this text. what do you know,and illustrator of the text. tell students to ...,vocabulary as they read and to think about the,and illustrator of the text. tell students to ...,?,and contradictions narrative nonfiction gives ...,way helps readers understand what happened and...
8,dok 2,have them describe what is happening in some o...,19 2/26/2018 5 40 23 am,in some of the,23 am read for understanding set a purpose hav...,tx a 5re_se_m1_inventor.indd,23 am read for understanding set a purpose hav...,they think they will,am read for understanding set a purpose have s...,have them describe what is happening in some o...
9,. he tied wires to his cats tails and rubbed t...,? (a narrator) how do you know? (the,and the pronouns,dok 2 targeted close read point of view explai...,read for understanding retell/summarize,6 7 mynotes 20 do not edit changes must be,read for understanding retell/summarize,28 am read for understanding retell/,long ago,? (a narrator) how do you know? (the