In [2]:
from sentence_transformers import SentenceTransformer
import operator
import regex as re
from pandas import DataFrame
import numpy as np
import umap
#import hdbscan
import matplotlib.pyplot as plt
import pandas as pd
import PyPDF2
import cleantext
from cleantext import clean

In [3]:
path = "/Users/kazotogbah/Desktop/ResearchDesignForBusinessAnalytics/HMH_box/OneCMS_Learning_Spine_English_Language_Arts2021012117.xlsx" 
skills = pd.io.excel.read_excel(path,skiprows=range(0,4),header=1)
skills

,Level 1: Domain,Level 2: Strand,Level 3: Substrand 1,Level 4: Substrand 2,Level 5: Substrand 3,Skill Title,Skill Description,Skill GUID,Skill Code,Lower Grade,Upper Grade
0,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Identify Intended Audience and Evaluate Its Im...,Identify an informational text's intended audi...,017ab281-a63f-4f41-928e-7d66f29d0bff,CA.GC.1a,K,12
1,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Identify Author's Purpose While Reading Text,Understand that authors write texts for differ...,5d958ee3-826a-444b-89be-047b54923cd0,CA.GC.1b,K,12
2,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Analyze How Author Advances Purpose While Reading,"While reading, analyze how the author advances...",efaa706c-b57a-442e-a9ec-bd4a4fd589d1,CA.GC.1c,K,12
3,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Determine Author's Perspective or Opinions Whi...,Determine the author's perspective and opinion...,015ace30-cf79-4f4e-b973-21bd939a5970,CA.GC.1d,K,12
4,Reading and Understanding Text and Media,Comprehending and Analyzing Written Text,General Reading Comprehension Skills,Understanding Author's Purpose and Perspective...,NaN,Evaluate Author's Credibility to Support Readi...,Identify and analyze an author's qualification...,8d26c54f-a2b6-48ef-9aa6-fad26f0475c5,CA.GC.1e,K,12
...,...,...,...,...,...,...,...,...,...,...,...
2289,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Haikus or Tankas,"Write haikus or tankas, following the structur...",e0653513-1af9-493c-99cc-ca26440a59cb,WT.WP.2.C4,K,12
2290,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Riddle Poems,Write riddle poems that require the reader to ...,97410ba5-9fc4-4684-97c4-9be529ceafe5,WT.WP.2.C5,K,12
2291,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Odes,"Write odes to praise people, events, objects, ...",d5d3e7af-d5b5-45f9-8320-77db880d3856,WT.WP.2.C6,K,12
2292,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Sonnets,Write sonnets following the structural charact...,7637f149-07f8-4ca0-84d7-5593e1b9211a,WT.WP.2.C7,K,12
2293,"Writing, Researching, Producing, and Presenting",Writing Types and Forms,Writing Poetry,Poetic Writing Types,NaN,Write Free Verse Poems,Write poems in free verse that depart from tra...,d774010e-382b-417f-842b-21dcc46a5a65,WT.WP.2.C8,K,12

In [4]:
path = "/Users/kazotogbah/Desktop/CapstoneWritting/hmh_data/grade5_corpus_clean_keywords_summarized_distilroberta5d6e638df6bbc73a104a58cba197d9c291bc143038ce348f209bb1ed29ec364b.pkl" 
unpickled_data = pd.read_pickle(path,compression='infer')
unpickled_data

,file,page,text,text_clean,text_clean_no_periods,text_clean_embedded,text_clean_no_periods_embedded,text_keywords,text_keywords_clean_embedded,text_clean_summarized,text_summarized_clean_embedded
0,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,1,GRADE 5\nTeacher™s \nGuide\nVolume\n1,grade 5 teacher s guide volume 1,grade 5 teacher s guide volume 1,"[0.117546454, -0.1289108, 0.024675569, 0.79411...","[0.117546454, -0.1289108, 0.024675569, 0.79411...",guide volume 1 grade 5 teacher,"[0.17422542, -0.30430984, -0.1412666, 0.402076...",grade 5 teacher s guide volume 1 .,"[0.09989826, -0.12482233, -0.074708804, 0.6445..."
1,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,2,Authors and Advisors\nAlma Flor Ada Ł Kylene B...,authors and advisors alma flor ada kylene beer...,authors and advisors alma flor ada kylene beer...,"[-0.1704829, 0.5890835, 0.4387237, 0.32914245,...","[-0.14373687, 0.5920101, 0.5037838, 0.35655, -...",probst shane templeton julie washington contri...,"[0.041675113, 0.48674396, 0.4313205, 0.3364311...",teachers and advisors david dockterman mindset...,"[-0.013609975, 0.29976955, 0.21084842, 0.41773..."
2,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,3,Copyright © 2020 by Houghton Mifflin Harcourt ...,copyright 2020 by houghton mifflin harcourt pu...,copyright 2020 by houghton mifflin harcourt pu...,"[-0.0028390083, 0.063993715, -0.029938823, 0.0...","[-0.023803977, 0.013359526, -0.032527126, 0.07...",isbn 978 0 544 46144 4 1 2 3 4 5 6 7 8 9 10 xx...,"[0.20285466, 0.5847995, 0.4128311, -0.00631434...",copyright 2020 by houghton mifflin harcourt pu...,"[0.2748426, -0.029980134, 0.083095424, -0.1134..."
3,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,4,CONTENTS\nPROGRAM OVERVIEW\nAuthors and Adviso...,contents program overview authors and advisors...,contents program overview authors and advisors...,"[0.09931215, -0.020393949, 0.19883995, 0.13973...","[0.09931215, -0.020393949, 0.19883995, 0.13973...",advisors ivv develop collaborative self direct...,"[0.046048887, 0.15412024, 0.35991096, 0.457981...",hmh into reading z combines the best practices...,"[0.3145923, -0.03275597, -0.05179701, 0.035828..."
4,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,5,HMH Into Reading\nŽ\n Authors and Advisors\nCa...,hmh into reading z authors and advisors carol ...,hmh into reading z authors and advisors carol ...,"[0.002761202, 0.20128998, 0.030401845, 0.45410...","[0.038746584, 0.112783305, 0.05895126, 0.50247...",professor emeritus georgia state university na...,"[0.13315715, 0.4420836, -0.06468263, 0.241299,...",nationally known lecturer on reading and writi...,"[0.18033423, -0.10298076, 0.0937723, 0.3509618..."
...,...,...,...,...,...,...,...,...,...,...,...
2563,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,224,"for specificity, W144\nstrengthen sentences, W...",for specificity w144 strengthen sentences w160...,for specificity w144 strengthen sentences w160...,"[0.07533929, 0.27126107, 0.42523658, 0.7635136...","[0.092685536, 0.27681655, 0.42898053, 0.638846...",specificity w144 strengthen sentences w160 str...,"[0.07472088, 0.34592706, 0.38472912, 0.508255,...",w108 r57 resources do not edit changes must be...,"[0.27958247, 0.11633515, 0.24163221, 0.2382852..."
2564,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,225,"spelling, frequently misspelled words\n, W343Œ...",spelling frequently misspelled words w343w347 ...,spelling frequently misspelled words w343w347 ...,"[0.160896, 0.42635867, 0.113605425, -0.2727297...","[0.1265479, 0.4114701, 0.20987032, -0.22350144...",early drafts w144 genre preferences w23 groupi...,"[0.358979, 0.31093988, 0.364606, 0.04616851, -...",misspelled words w343w347 connect to writing w...,"[0.047042217, 0.46796146, 0.14991142, -0.38447..."
2565,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,226,"peer encouragement, W188\npersuasive words and...",peer encouragement w188 persuasive words and p...,peer encouragement w188 persuasive words and p...,"[-0.08801644, 0.30615604, 0.16125068, -0.09681...","[-0.08801644, 0.30615604, 0.16125068, -0.09681...",research reports w115 review w321 topic w57 ch...,"[-0.14283302, 0.08291002, 0.032422204, 0.49036...",w2 w36 w52 w134 w166 w182 research w106 traits...,"[-0.11839676, 0.18371567, 0.017508658, 0.56517..."
2566,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,227,"consistent verb tenses, W265\nreview, W266\nve...",consistent verb tenses w265 review w266 verb p...,consistent verb tenses w265 review w266 verb p...,"[-0.04153027, 0.33976993, -0.03514204, 0.58501...","[-0.04524856, 0.32852265, -0.0004498493, 0.484...",throughout lessons w word bank w6 w22 w39 w54 ...,"[-0.17300694, -0.15565056, 0.101209015, 0.2080...",w2 w4 w5 and throughout lessons w word bank w6...,"[0.111897975, 0.09618612, -0.056099165, 0.4386..."
2567,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,228,LV 51599850Module 1 Inventors at Work\nModule ...,lv 51599850module 1 inventors at work module 2...,lv 51599850module 1 inventors at work module 2...,"[-0.1708624, 0.20013708, 0.036242086, 0.450545...","[-0.1708624, 0.20013708, 0.036242086, 0.450545...",animals module 11 genre study nonction module ...,"[-0.2275486, 0.14347199, 0.012625823, 0.665472...",lv 51599850module 1 inventors at work module 2...,"[-0.14776115, 0.24512847, 0.017764378, 0.42249..."

In [4]:
unpickled_data['text_clean']

0                        grade 5 teacher s guide volume 1
1       authors and advisors alma flor ada kylene beer...
2       copyright 2020 by houghton mifflin harcourt pu...
3       contents program overview authors and advisors...
4       hmh into reading z authors and advisors carol ...
                              ...
2563    for specificity w144 strengthen sentences w160...
2564    spelling frequently misspelled words w343w347 ...
2565    peer encouragement w188 persuasive words and p...
2566    consistent verb tenses w265 review w266 verb p...
2567    lv 51599850module 1 inventors at work module 2...
Name: text_clean, Length: 2568, dtype: object

In [5]:
unpickled_data['text_clean'][123]

'project checkpoint write and create have students work in groups using printable project 1.2 to guide them as they continue work on the project. groups should complete the following over the course of the week research and draft a business plan for a new invention. discuss the details of the plan including function of the invention target market and profit margin. revise their drafts to improve purpose or detail. edit their drafts for conventions. create a prototype drawing of their invention. reading remake (use in lessons 610.) have students complete the write a news story activity for winds of hope printable reading remake 1 . ask students to explain to one another how their news stories show an understanding of the selection. write an expository essay (use in lessons 610.) have students use printable peer conferencing routine to discuss their writing. tell peers to use the tips on my book page 53 as they review the work of others and offer feedback. writing workshop have students work on a piece of writing. depending on where students are in their writing they may use the time to prewrite draft revise edit or publish. students may choose from among tasks such as these " revise drafts. " publish. writing center listener s choice have students listen to winds of hope or a leveled reader of their choice. tell them to add the title to their printable listening log as well as listing the listening skills they used a summary of the selection and questions they have about the selection or book. keyboarding have students practice keyboarding using printable keyboarding 1.2 . project center digital station module 1 week 2 printable keyboarding 1.2 printable project 1.2 printable reading remake 1 name find the delete or backspace key arrow keys and slide. find the delete key at the top right of the keyboard. on some keyboards there may be a key named backspace and a key named delete. if your keyboard has both of these keys use the key named backspace. stretch your finger to tap the delete key. use delete to delete errors when typing. find the arrow keys at the bottom right of the keyboard. use the arrow keys to move the cursor on the screen. find the slide at the far right of the screen. use the mouse or touchpad to click and drag the slide to move the page up ordown. practice keyboarding. key the marks words and spaces in each line below. do not key the numbers. when you finish go to file/save to save your work as keyboarding 1.2 . 1. go to file/open and open keyboarding 1.1. 2. use the slide to find line number 2. use the arrow keys to navigate to the beginning of the line. 3. use the arrow keys and the delete key to delete the first and last letters in the line. 4. use the arrow keys to move to line number 8. 5. use the delete key to delete the first three words in the line. navigation start from the home row. place your hands on the home row. keyboarding 1.2 space a s d f g h j k l fl z x c v b n m < > . ? / ~ \' ! 1 @ 2 # 3 <cur> 4 % 5 ^ 6 & 7 * 8 ( 9 ) 0 s _ + = delete q w e r t y u i o p { [ } ] tab | \\ cap lock enter/ return shift shift houghton mifflin harcourt publishing company. all rights reserved. grade 5 printable intoreading_g5_keyboarding_m1_printable_w2.indd 1 4/12/18 12 00 am name project 1.2 create your own invention u se research to choose an invention write a business plan and draw a prototype of your invention. week 2 write and create 1. meet with y our group to review ideas for an invention to use as a focus of your presentation. use the group document or visual fiidea boardfl as you discuss. 2. de velop a plan so you know who is responsible for each part of the project. 3. o rganize your research. outline the purpose of the invention the target market (buyer) and what it will cost to make the invention. 4. plan y our writing. be sure you include important information such as how this invention solves a problem or makes a task easier. 5. d raft your business plan. explain why this invention should be made and who it will benefit. 6. p ause to be sure that everyone is in agreement about the direction of the project. discuss what you can do to improve the writing. 7. re vise your writing. make changes as needed to strengthen the organization purpose or level of detail in your writing. 8. plan visual audio multimodal or other additions to make your project come to life. create a prototype drawing of your invention to share during your presentation. houghton mifflin harcourt publishing company. all rights reserved. grade 5 printable ngr_g5_anc_m1_projectprintable w2.indd 1 16/03/18 7 15 am t85 literacy centers do not edit changes must be made through fifile infofl correctionkey=tx c nl b va c'

In [7]:
unpickled_data['text_clean_no_periods']

0                        grade 5 teacher s guide volume 1
1       authors and advisors alma flor ada kylene beer...
2       copyright 2020 by houghton mifflin harcourt pu...
3       contents program overview authors and advisors...
4       hmh into reading z authors and advisors carol ...
                              ...
2563    for specificity w144 strengthen sentences w160...
2564    spelling frequently misspelled words w343w347 ...
2565    peer encouragement w188 persuasive words and p...
2566    consistent verb tenses w265 review w266 verb p...
2567    lv 51599850module 1 inventors at work module 2...
Name: text_clean_no_periods, Length: 2568, dtype: object

In [8]:
unpickled_data['text_keywords']

0                          guide volume 1 grade 5 teacher
1       probst shane templeton julie washington contri...
2       isbn 978 0 544 46144 4 1 2 3 4 5 6 7 8 9 10 xx...
3       advisors ivv develop collaborative self direct...
4       professor emeritus georgia state university na...
                              ...
2563    specificity w144 strengthen sentences w160 str...
2564    early drafts w144 genre preferences w23 groupi...
2565    research reports w115 review w321 topic w57 ch...
2566    throughout lessons w word bank w6 w22 w39 w54 ...
2567    animals module 11 genre study nonction module ...
Name: text_keywords, Length: 2568, dtype: object

In [9]:
unpickled_data['text_clean_summarized']

0                      grade 5 teacher s guide volume 1 .
1       teachers and advisors david dockterman mindset...
2       copyright 2020 by houghton mifflin harcourt pu...
3       hmh into reading z combines the best practices...
4       nationally known lecturer on reading and writi...
                              ...
2563    w108 r57 resources do not edit changes must be...
2564    misspelled words w343w347 connect to writing w...
2565    w2 w36 w52 w134 w166 w182 research w106 traits...
2566    w2 w4 w5 and throughout lessons w word bank w6...
2567    lv 51599850module 1 inventors at work module 2...
Name: text_clean_summarized, Length: 2568, dtype: object

In [16]:
skills["Skill Description"]

0       Identify an informational text's intended audi...
1       Understand that authors write texts for differ...
2       While reading, analyze how the author advances...
3       Determine the author's perspective and opinion...
4       Identify and analyze an author's qualification...
                              ...
2289    Write haikus or tankas, following the structur...
2290    Write riddle poems that require the reader to ...
2291    Write odes to praise people, events, objects, ...
2292    Write sonnets following the structural charact...
2293    Write poems in free verse that depart from tra...
Name: Skill Description, Length: 2294, dtype: object

In [17]:
skill_desc=skills["Skill Description"]

In [15]:
summarized_text=unpickled_data['text_clean_summarized']
no_period_text=unpickled_data['text_clean_no_periods']
keywords_text=unpickled_data['text_keywords']
clean_text=unpickled_data['text_clean']

---
# Q&A Model

In [5]:
from transformers import BertForQuestionAnswering
#from transformers import AutoModel

In [6]:
model = BertForQuestionAnswering.from_pretrained('deepset/bert-base-cased-squad2')
#model = BertForQuestionAnswering.from_pretrained('deepset/electra-cased-squad2')

In [7]:
from transformers import AutoTokenizer
#from transformers import BertTokenizer

In [8]:
tokenizer = AutoTokenizer.from_pretrained('deepset/bert-base-cased-squad2')

In [9]:
from transformers import pipeline

In [10]:
nlp = pipeline('question-answering',model =model,tokenizer=tokenizer)

____
## skills_to_questions

In [11]:
import pandas as pd
import numpy as np
skills_to_questions = []
skillnum = -1
concat_1 = "How to "
concat_2 = "?"
for skill in skills["Skill Description"]:
    skillnum = skillnum+1
    skills_to_questions.append(concat_1 + skills["Skill Description"][skillnum] + concat_2)
    
skills_to_questions

["How to Identify an informational text's intended audience while reading, and analyze how it affects the author's development of a text?",
 "How to Understand that authors write texts for different purposes: to inform, persuade, entertain, or share thoughts or feelings; and identify author's purpose(s) while reading text?",
 'How to While reading, analyze how the author advances the purpose of a text in terms of style and use of text structure, language and rhetoric (e.g., formal or informal language, figures of speech, tone, persuasiveness), and evaluate the degree to which the author achieved the purpose of the text?',
 "How to Determine the author's perspective and opinions, including underlying values and beliefs, based on explicit and implicit information while reading text?",
 "How to Identify and analyze an author's qualifications to evaluate the author's credibility?",
 "How to While reading, evaluate how an author's personal, cultural, and historical background impacts their purpose for writing and the structure and meaning of a text?",
 "How to Distinguish the author's opinions from one's own opinions while reading text?",
 "How to While reading, identify an author's opinions, beliefs, and attitudes that bias text based on explicit and implicit information from the text or information about the author's background?",
 "How to Evaluate how an author's perspective or opinions impact a text while reading?",
 "How to While reading, compare and contrast how different authors' personal, cultural, and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?",
 'How to Identify the author’s purpose in individual paragraphs or sections of a text?',
 'How to Set a purpose for reading text?',
 "How to Preview the text to gain information about a text's author, genre, topic, and structure, creating a context to inform the text’s meaning and significance while reading?",
 'How to Make and confirm or refute predictions while reading in order to engage with a text and deepen comprehension?',
 "How to Make personal connections between a text and one's own experiences, feelings, and perspectives to actively read and comprehend deeply?",
 'How to Connect a text to what is known about the world and the way things are outside the self to actively read and comprehend deeply?',
 'How to Connect information between texts during or after reading to aid with comprehending the new text and to broaden knowledge and gain new perspectives?',
 "How to Ask and answer questions while reading to help clarify comprehension, deepen understanding of a text's literal meaning, and demonstrate comprehension?",
 'How to Ask and answer interpretive and evaluative questions while reading to support comprehension and analysis of a text and demonstrate comprehension?',
 'How to Visualize situations while reading to develop a deeper understanding and enhance recall of the text?',
 'How to Use graphic organizers to aid in comprehension and analysis of text while reading or for later use?',
 'How to Use note-taking and annotation strategies while reading to monitor comprehension of text or for later use?',
 'How to While reading, periodically check for coherence and understanding of main ideas, events, and concepts?',
 'How to When comprehension breaks down during reading, use strategies to adjust, such as rereading, adjusting reading rate, reading ahead, summarizing, or questioning difficult parts of the text?',
 'How to Combine information gained from reading a text with one’s own academic and personal knowledge to make inferences about what is not stated directly?',
 'How to Distinguish between works of fiction and nonfiction while reading, based on text content and features?',
 'How to Choose texts for independent reading based on personal preferences of topics, authors and genres, or reviews or recommendations?',
 'How to Access prior knowledge to support comprehension and evaluation of a text while reading?',
 'How to Adjust reading style (e.g., skimming, re-reading, close reading) based on purpose for reading?',
 'How to Build background knowledge to support comprehension and evaluation of a text while reading?',
 'How to While reading, distinguish true, realistic, and fantastical literary works and elements of literary works?',
 'How to Generalize information gained from reading a text to make a prediction about a related situation or text?',
 'How to Distinguish between literary and informational texts while reading?',
 'How to Evaluate the plausibility of predictions about text based on text evidence while reading?',
 'How to Draw conclusions from reading text, based on a combination of information from the text and background knowledge, to make decisions, arrive at opinions, or determine results?',
 'How to Use a combination of information from text and background knowledge to make valid generalizations about a subject based on reading?',
 'How to Cite text details, examples and evidence from reading to support inferences, conclusions, interpretations, and arguments?',
 'How to Engage in classroom, small group, or partner conversations about the text during and after reading to build on thoughts and ideas, and to deepen understanding of the text?',
 'How to Write a response to text after reading to share thoughts, feelings, ideas, or opinions about what was read, to aid recall, or to deepen comprehension?',
 'How to Respond to a text after reading by creating an illustration that recounts events, ideas, and details about the text?',
 'How to While reading, analyze the connections, relationships, or interactions between individuals, ideas, or events in a text and explain how they develop throughout the course of the text?',
 'How to While reading, compare and contrast works of fiction to works of nonfiction that are about the same or similar topic, events, or people?',
 "How to While reading, analyze how a selection from a text fits into the overall structure of the text and contributes to the text's development?",
 'How to While reading, evaluate the degree to which the meaning of a text is clear or ambiguous and the information in a text is consistent or inconsistent, and determine the impact on the meaning and significance of the text?',
 'How to Evaluate how different mediums present the same text or topic (e.g., books, oral performances, presentations, films), and evaluate similarities and differences in how each medium interprets or represents it?',
 'How to Distinguish between an objective summary and a critique or review of text?',
 'How to Evaluate summaries of text for accuracy, meaning, or objectivity?',
 'How to Compare and contrast the structure and organization of two or more informational texts while reading?',
 'How to Synthesize ideas from reading texts across genres to draw conclusions about the texts and develop knowledge?',
 'How to Reflect and respond from a personal perspective (e.g., level of personal enjoyment, what was learned, agreement/disagreement) after reading text?',
 'How to Evaluate the quality and relevance of evidence from text when citing evidence to support inferences, conclusions, interpretations, and arguments?',
 "How to Paraphrase texts or parts of texts in one's own words after reading, retaining the meaning, structure, and order of the text?",
 'How to Synthesize ideas from different parts within a text while reading to understand how the ideas fit together and contribute to the overall significance of the text?',
 'How to Synthesize ideas from written texts with texts read aloud and/or media to draw conclusions and develop knowledge?',
 'How to Summarize texts objectively after reading, providing a shortened version of the text that retains the main points?',
 'How to Orally summarize texts objectively after reading, providing a shortened version of the text that retains the main points?',
 'How to Write objective summaries of text after reading, providing a shortened version of the text that retains the main points?',
 'How to Collaborate to produce writing or media after reading text?',
 "How to Understand that graphic features, such as illustrations, maps, or charts, contribute to a text's meaning, and identify, interpret, and use graphic features while reading?",
 'How to While reading, evaluate the degree to which the graphic features in a text contribute important information that cannot be conveyed by the words alone?',
 'How to Understand that text features, including chapters, headings, sub-headings, and bullets, are used to provide organization and visual interest to a text, and identify, interpret, and use text features to locate information while reading text?',
 'How to Evaluate the degree to which text features support comprehension while reading text?',
 'How to Synthesize information from multiple graphic features to draw conclusions while reading text?',
 'How to Understand that information is provided by graphic features and by words, and distinguish information that is provided by graphics and by words while reading text?',
 'How to Integrate information from text features and/or graphic features to comprehend text while reading?',
 "How to Understand that imagery consists of words that appeal to readers' senses and identify imagery while reading text?",
 'How to Understand that parallelism is a repetition of grammatically identical words or phrases in a sentence to give it a balance and rhythm; and identify parallelism while reading text?',
 "How to While reading text, evaluate the degree to which parallelism provides balance and rhythm to a sentence and supports the author's purpose?",
 'How to Understand that dialogue is a conversation between two or more characters, and identify dialogue while reading text?',
 'How to Understand that a dialect is the way a group of people speak a language based on location or background and that authors use dialect to help define characters, and identify the use of dialects while reading text?',
 'How to While reading text, evaluate the degree to which use of dialects helps define characters?',
 'How to Understand that register is the degree of formality in language, and identify register while reading text?',
 'How to While reading, evaluate the degree to which use of register helps define characters and sets the tone of a work of literature?',
 'How to Understand that mood is the emotional atmosphere conveyed by an author, and identify the mood of a text while reading?',
 "How to While reading, analyze the details that helped create a text's mood, and evaluate their effectiveness?",
 "How to Understand that tone conveys an author's attitudes and viewpoints toward the topic of the literary work, and identify the tone of a text while reading?",
 "How to While reading, analyze an author's tone or attitude toward a topic and identify details that communicate the tone?",
 "How to Understand that an author's style is the overall voice of the author, based on use of language and literary devices to give the work meaning, and describe authors' styles while reading?",
 'How to While reading classical and modern works of literature, identify and compare and contrast archetypes?',
 'How to While reading classical and modern works of literature, identify and compare and contrast motifs?',
 'How to Understand that language can be used literally and figuratively, and identify literal and figurative uses of language while reading text?',
 "How to While reading, analyze the use of figurative language for imagery or rhetorical effect, and evaluate its impact on a text and the degree to which it advances the author's purpose?",
 "How to While reading text, analyze how use of idioms impacts tone and advances the author's purpose?",
 'How to Understand that oxymorons are combinations of words with contrasting meanings and that paradoxes are combinations of self-contradictory statements, and identify oxymorons and paradoxes while reading?',
 "How to While reading text, analyze how use of contradictory language, including  oxymorons and paradoxes, impacts tone and advances the author's purpose in a text?",
 "How to While reading text, analyze author's use of literary devices to determine how they impact a text and the degree to which they achieve their purposes?",
 'How to Understand that an anecdote is a very short story about an incident that can add meaning, interest, and informal evidence to a text or dialogue through qualities such as humor, inspiration, or a personal memory, and identify anecdotes while reading text?',
 'How to Evaluate the degree to which anecdotes achieve their purpose while reading text?',
 'How to Understand that stereotyping is the attribution of a trait or traits to all members of a group, rather than treating group members as individuals with many different traits, and identify examples of stereotyping while reading text?',
 'How to Analyze examples of imagery while reading text to determine which senses they appeal to and the degree to which they add to the reader’s experience?',
 "How to While reading text, evaluate the degree to which stereotyping impacts the text's development?",
 "How to While reading text, analyze an author's use of euphemisms and evaluate how they are used to soften the author's message?",
 "How to Understand that euphemisms are words or phrases that are more polite or indirect and used to soften another word or phrase, or to neutralize a word's connotation; and identify and interpret euphemisms while reading text?",
 "How to While reading text, analyze an author's voice or style to understand the author's attitude, and evaluate the impact of voice on the meaning the text?",
 "How to While reading text, Analyze how use of puns impacts tone and advances the author's purpose?",
 'How to Understand that sound devices use patterns of sound repetition or words that suggest sounds to impact the meaning and mood of writing, and identify sound devices such as assonance, consonance, alliteration, or onomatopoeia while reading text?',
 'How to While reading text, evaluate how use of sound devices impacts the meaning and mood of the text and enhances its aesthetic qualities?',
 "How to While reading, compare and contrast different authors' use of literary devices to determine how they impact the texts and the degree to which they achieve their purposes?",
 'How to Understand that idioms are phrases that have a specific meaning different from their literal meaning, and identify idioms while reading text?',
 'How to Understand that authors repeat words and phrases for emphasis, and identify repetition in while reading text?',
 'How to Understand that proverbs and adages are phrases that communicate general truths or advice that go beyond their literal meaning, and identify proverbs and adages while reading text?',
 'How to Understand that extended metaphors are figurative comparisons developed at length throughout literary works, and identify examples of extended metaphors while reading text?',
 'How to While reading text, analyze the meaning of extended metaphors and the degree to which they achieve their purpose?',
 'How to Understand that similes and metaphors draw comparisons between two different ideas or things but that similes use "like" or "as" to draw the comparison and metaphors do not; and identify similes and metaphors while reading text?',
 'How to While reading text, analyze the purposes of similes and metaphors and the degree to which they achieve their purposes?',
 'How to Understand that analogies use similes and metaphors to compare two very different things and identify analogies while reading text?',
 'How to While reading text, analyze the effects that analogies have on the meaning of what they compare?',
 'How to Understand that personification attributes human qualities to animals, ideas, and objects, and identify personification while reading text?',
 'How to While reading text, analyze examples of personification, and evaluate how they affect the readers’ perspective of the object of personification?',
 'How to Understand that a symbol is an object that represents something else and gives it a special and deeper meaning, and identify symbols and interpret what they represent while reading text?',
 "How to While reading text, analyze why an author used symbols  and how the symbols added to the reader's understanding of the text?",
 'How to Understand that allegories are narratives told on literal and symbolic levels in order to communicate about abstract ideas, and identify examples of allegories while reading text?',
 'How to While reading text, analyze the meanings of the symbolism found in allegories and evaluate their effectiveness in communicating the message of the text?',
 'How to Understand that an allusion is a short, indirect reference to a person or thing that has a particular significance (e.g., cultural, historical), and identify allusions while reading text?',
 'How to Evaluate the degree to which an allusion achieves its purpose in a text while reading?',
 'How to Understand that irony uses language to convey a message that is different from its literal meaning, and identify and interpret irony while reading text?',
 'How to Understand the similarities and differences between verbal, situational, and dramatic irony, and identify each type while reading?',
 'How to While reading, evaluate the degree to which irony deepens understanding of and adds interest to text?',
 'How to Understand that sarcasm uses ironic language to mock, insult, or convey contempt, and identify and interpret sarcasm while reading text?',
 'How to While reading text, evaluate the degree to which sarcasm deepens understanding of and adds interest?',
 'How to Understand that hyperbole is an extreme exaggeration to emphasize a point or for dramatic effect, and identify hyperbole while reading text?',
 "How to While reading text, evaluate the degree to  which hyperbole emphasizes points and impacts the reader's interest?",
 "How to Understand that satire is a device that points out a person's or group's negative qualities by using humor, exaggeration, and irony for the purpose of exposing those qualities; and identify examples of satire while reading?",
 'How to While reading, evaluate the degree to which satirical texts achieve their purpose?',
 "How to While reading text, evaluate the degree to which an author's word choices are clear, accurate, and appropriate to convey the author's message effectively?",
 'How to Identify the topic that the author addresses in a informational text while reading?',
 'How to Identify text-level main ideas in informational texts while reading?',
 'How to Identify paragraph- or section-level main ideas in informational text while reading?',
 'How to While reading, identify key details that support the main ideas of texts, paragraphs, or sections of text?',
 'How to Identify and analyze conflicting information across two or more informational texts while reading?',
 'How to While reading informational text, analyze the development of main ideas and the use of key details to support them?',
 'How to Identify paragraph- or section-level topics in informational texts while reading?',
 'How to While reading, evaluate the importance and relevance of key details that support the main ideas of informational texts, paragraphs, or sections of text?',
 "How to Understand that scope is a text's coverage of a topic, which can range from narrow (covering few details related to a topic) to broad (covering many details related to a topic), and identify the scope of informational texts while reading?",
 'How to Identify individuals, ideas, concepts, or events in informational texts while reading?',

In [12]:
skills_to_questions[0]

"How to Identify an informational text's intended audience while reading, and analyze how it affects the author's development of a text?"

In [13]:
skills_to_questions.dtypes

AttributeError: 'list' object has no attribute 'dtypes'

---
# Bert Q&A with Clean text with Periods

In [17]:
len(skills_to_questions)

2294

In [16]:
import pandas as pd
import numpy as np
qa_scores = []
page = -1
skillnum = -1
for text in unpickled_data['text_clean'] :
    page = page+1
    context = unpickled_data['text_clean'][page]
    score=[]
    for skill in skills_to_questions:
        skillnum = skillnum+1
        question = skills_to_questions[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
               
score_df_clean_text = pd.DataFrame(qa_scores)

IndexError: list index out of range

In [22]:
import pandas as pd
import numpy as np
qa_scores = []
page = -1
skillnum = 0
for text in unpickled_data['text_clean'] :
    page = page+1
    context = unpickled_data['text_clean'][page]
    score=[]
    for skillnum in range(0,2293):
        question = skills_to_questions[skillnum]
        skillnum = skillnum+1
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df_clean_text = pd.DataFrame(qa_scores)

KeyboardInterrupt:

In [23]:
score_df_clean_text

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.002544,0.000379,0.012029,0.011135,0.059135,0.034940,0.001362,0.051135,0.012390,0.014631,...,7.983492e-04,0.004413,0.027669,0.005672,0.142292,0.017373,0.024859,0.016607,0.011929,0.025819
1,0.009541,0.000006,0.001503,0.000134,0.001479,0.001029,0.000182,0.002389,0.000207,0.011897,...,9.199142e-06,0.000345,0.000141,0.000023,0.000010,0.003698,0.004070,0.000801,0.023567,0.000347
2,0.000978,0.011153,0.000023,0.001879,0.004777,0.000014,0.000011,0.131737,0.001756,0.001306,...,3.476415e-07,0.009554,0.000582,0.000144,0.000029,0.028121,0.012264,0.226880,0.003651,0.000604
3,0.012175,0.000775,0.000012,0.000752,0.027539,0.000024,0.000111,0.015306,0.014004,0.001077,...,5.585578e-06,0.002657,0.001682,0.001031,0.000007,0.001646,0.000805,0.045596,0.002146,0.000552
4,0.000498,0.000412,0.000081,0.001369,0.012132,0.000190,0.000009,0.031485,0.000398,0.001310,...,5.330083e-06,0.002909,0.000141,0.000106,0.000009,0.005927,0.004270,0.003565,0.000408,0.005436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.248521,0.000150,0.000351,0.000476,0.009815,0.000544,0.000186,0.014742,0.011920,0.048688,...,2.831024e-05,0.002698,0.000807,0.000089,0.000431,0.055841,0.041121,0.003029,0.007054,0.004654
96,0.090001,0.004711,0.006325,0.006481,0.067263,0.137082,0.000640,0.380689,0.005014,0.281055,...,1.365399e-04,0.001850,0.000497,0.000423,0.007223,0.103520,0.091799,0.031859,0.114954,0.012871
97,0.001776,0.000101,0.000100,0.000042,0.000258,0.000253,0.000021,0.012379,0.000315,0.012032,...,6.164498e-04,0.001474,0.008613,0.002091,0.000062,0.034072,0.029439,0.025186,0.042023,0.008124
98,0.001648,0.002688,0.001238,0.025162,0.004421,0.004455,0.000016,0.016457,0.001481,0.006448,...,1.840093e-04,0.047020,0.000789,0.000096,0.007829,0.099290,0.036847,0.016019,0.087949,0.006337
99,0.000815,0.000062,0.000125,0.000081,0.005715,0.000241,0.000006,0.005120,0.000110,0.001313,...,1.061606e-06,0.037873,0.003544,0.000059,0.001729,0.016538,0.084446,0.043629,0.002498,0.000391

In [ ]:
range()

---
# Model Testing with Clean text with no Periods

In [20]:
import pandas as pd
import numpy as np
qa_scores = []
page = 40
skillnum = 0
for page in range(40,100):
    page = page+1
    context = no_period_text[page]
    score=[]
    for skillnum in range(50):
        skillnum = skillnum+1
        question = skill_desc[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df_no_period_text = pd.DataFrame(qa_scores)

In [24]:
score_df_no_period_text

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.003155,0.000283,0.014772,0.008035,0.058744,0.029881,0.007208,0.045952,0.019757,0.014163,...,2.490999e-03,0.008367,0.034804,0.011030,0.120156,0.022645,0.020571,0.020372,0.011146,0.029562
1,0.006288,0.000048,0.000614,0.000121,0.001540,0.003036,0.000094,0.001844,0.000287,0.004766,...,2.532166e-06,0.002457,0.000020,0.000017,0.000004,0.004942,0.013148,0.004848,0.019439,0.000611
2,0.005665,0.035660,0.000104,0.002679,0.007235,0.000036,0.000007,0.120570,0.001707,0.003414,...,3.606931e-07,0.011244,0.000707,0.000219,0.000033,0.030635,0.010872,0.217956,0.003719,0.000776
3,0.000675,0.003170,0.000047,0.001060,0.040118,0.000040,0.000029,0.009893,0.103055,0.000970,...,4.637174e-05,0.000785,0.000041,0.000003,0.000002,0.003799,0.001380,0.052505,0.005166,0.001093
4,0.000487,0.000870,0.000107,0.002498,0.002775,0.000173,0.000010,0.051916,0.003173,0.001486,...,8.006306e-07,0.000920,0.000520,0.001091,0.000008,0.004983,0.008483,0.001105,0.000306,0.004487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.384406,0.000389,0.000122,0.000888,0.009019,0.000375,0.000225,0.009981,0.023694,0.016197,...,3.664429e-05,0.011335,0.002597,0.000106,0.002470,0.015401,0.027034,0.006643,0.003098,0.017998
96,0.024933,0.002039,0.002139,0.001441,0.019912,0.039041,0.000116,0.208322,0.052548,0.008126,...,4.515189e-05,0.089267,0.000763,0.006167,0.005411,0.104918,0.055774,0.031436,0.041923,0.023439
97,0.004502,0.000044,0.032193,0.000810,0.003312,0.001883,0.000352,0.080485,0.031811,0.005608,...,3.389484e-04,0.002024,0.024614,0.003524,0.035467,0.043243,0.010997,0.001946,0.038845,0.017618
98,0.001371,0.000932,0.002057,0.059560,0.024910,0.000555,0.000067,0.037348,0.064714,0.049892,...,1.476641e-04,0.017338,0.001203,0.001196,0.061397,0.319430,0.072858,0.036759,0.059173,0.010656
99,0.001763,0.007845,0.000423,0.000806,0.004745,0.000757,0.000101,0.043715,0.004511,0.006461,...,9.175513e-06,0.030881,0.001004,0.000155,0.006134,0.027406,0.014455,0.094457,0.010538,0.002108

---
# Model Testing with Summerized text

In [21]:
import pandas as pd
import numpy as np
qa_scores = []
page = 40
skillnum = 0
for page in range(40,100):
    page = page+1
    context = summarized_text[page]
    score=[]
    for skillnum in range(50):
        skillnum = skillnum+1
        question = skill_desc[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df_summarized_text = pd.DataFrame(qa_scores)

In [25]:
score_df_summarized_text

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.003827,0.000220,0.016501,0.000589,0.026375,0.031419,0.001867,0.026469,0.018581,0.009188,...,0.000701,0.004176,0.020897,0.008372,0.110297,0.013914,0.013122,0.025809,0.012533,0.019185
1,0.022472,0.009610,0.008112,0.012733,0.052541,0.024781,0.001519,0.056218,0.027293,0.052842,...,0.000343,0.021586,0.000925,0.003766,0.000876,0.063776,0.062770,0.026883,0.045882,0.060201
2,0.062856,0.046639,0.010010,0.007959,0.031205,0.003551,0.002375,0.024082,0.025575,0.017636,...,0.000033,0.057036,0.041739,0.007911,0.000038,0.079762,0.151628,0.110157,0.049958,0.011967
3,0.128582,0.114467,0.058453,0.290906,0.027749,0.034921,0.009192,0.145411,0.013042,0.094754,...,0.006761,0.130020,0.088897,0.021981,0.017902,0.026610,0.038787,0.126829,0.190558,0.181068
4,0.020403,0.016787,0.009427,0.015987,0.029173,0.006041,0.003121,0.031200,0.020539,0.025072,...,0.000057,0.011956,0.030724,0.017287,0.012391,0.078243,0.110034,0.117226,0.056222,0.019516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.024465,0.015430,0.009634,0.003588,0.043363,0.029552,0.005695,0.047206,0.010245,0.024686,...,0.001480,0.068614,0.014437,0.029025,0.037561,0.063474,0.208507,0.193099,0.048315,0.040553
96,0.023925,0.123455,0.027344,0.003410,0.162871,0.026142,0.016100,0.119157,0.040859,0.011162,...,0.002417,0.032537,0.025641,0.017377,0.003502,0.018117,0.156484,0.036686,0.014082,0.012613
97,0.123099,0.059406,0.084798,0.000026,0.035447,0.037345,0.019201,0.077228,0.062664,0.030522,...,0.006365,0.061285,0.091933,0.143713,0.287579,0.165790,0.281503,0.107370,0.190588,0.042917
98,0.047650,0.006267,0.013263,0.001036,0.103534,0.016214,0.008051,0.067560,0.029032,0.049667,...,0.002003,0.093280,0.067200,0.055815,0.022217,0.184729,0.097745,0.184476,0.089984,0.077598
99,0.158679,0.015200,0.025759,0.018416,0.072777,0.014523,0.045324,0.128160,0.084350,0.277084,...,0.002414,0.099289,0.075670,0.024124,0.000093,0.178523,0.192974,0.060512,0.046499,0.043989

---
# Model Testing with keywords text

In [22]:
import pandas as pd
import numpy as np
qa_scores = []
page = 40
skillnum = 0
for page in range(100):
    page = page+1
    context = keywords_text[page]
    score=[]
    for skillnum in range(50):
        skillnum = skillnum+1
        question = skill_desc[skillnum]
        score.append(nlp({'context':context,'question':question})['score'])
    qa_scores.append(score)
        
        
score_df_keywords_text= pd.DataFrame(qa_scores)

In [26]:
score_df_keywords_text

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.048564,0.075910,0.067253,3.567632e-02,0.482396,0.095219,0.030207,0.406459,0.186738,0.368218,...,0.003503,0.250423,0.047005,0.019679,3.041070e-01,0.327053,0.199887,0.236297,0.106218,0.243120
1,0.000872,0.000020,0.000090,4.816059e-04,0.000581,0.001732,0.000031,0.003688,0.000147,0.003275,...,0.000004,0.000111,0.000097,0.000636,2.595749e-04,0.001881,0.000517,0.000045,0.000810,0.000905
2,0.019609,0.000154,0.001240,8.094450e-03,0.000872,0.000052,0.000041,0.026437,0.000867,0.001653,...,0.000006,0.002212,0.000305,0.000131,2.958323e-05,0.010247,0.103946,0.164214,0.000851,0.002876
3,0.002049,0.003054,0.000979,4.921209e-03,0.004185,0.000246,0.000194,0.013449,0.001292,0.001997,...,0.000823,0.018169,0.000244,0.000356,4.414463e-02,0.023808,0.008977,0.046543,0.004512,0.012310
4,0.000686,0.000204,0.000123,1.009848e-03,0.000755,0.000126,0.000031,0.018979,0.000278,0.001339,...,0.000013,0.000258,0.000095,0.000301,3.650308e-05,0.002243,0.001433,0.001895,0.000396,0.000399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.059877,0.000626,0.001010,2.790870e-02,0.009203,0.001172,0.000165,0.012187,0.003368,0.010509,...,0.000018,0.000711,0.001213,0.000310,1.897739e-04,0.005855,0.033663,0.000877,0.041525,0.010955
96,0.028860,0.000044,0.000033,3.066924e-04,0.042817,0.000301,0.000020,0.002371,0.002434,0.034852,...,0.000045,0.000180,0.000097,0.000011,3.900017e-05,0.001583,0.001444,0.000009,0.027701,0.000781
97,0.000158,0.000096,0.000003,1.195854e-07,0.000002,0.000010,0.000093,0.000501,0.000488,0.000037,...,0.000014,0.000507,0.001246,0.000034,8.566252e-07,0.004344,0.000521,0.000310,0.029824,0.000059
98,0.012091,0.000017,0.001921,3.092110e-05,0.000744,0.000435,0.000131,0.001403,0.000340,0.000016,...,0.000052,0.000067,0.001521,0.002004,4.113488e-06,0.001300,0.001635,0.000006,0.058860,0.000008
99,0.000211,0.000011,0.000250,1.222846e-04,0.000486,0.003338,0.000069,0.045854,0.000780,0.000838,...,0.000082,0.000461,0.000276,0.000034,2.373199e-05,0.053138,0.003201,0.000791,0.001220,0.000636

___
## Bert Q&A

In [1]:
concat_1 = "How to "
concat_2 = "?"
skill_1 = concat_1 + skill_desc[0] + concat_2
skill_1

NameError: name 'skill_desc' is not defined